### ISSUE TITLE
Leading zeros on integer arguments are not allowed.

### ISSUE THREAD

**Issue by grinder213** [jarro2783/cxxopts#101]
I'm using cxxopts (1.4.2) for a CLI app which handles register- reads and writes in memory mapped hardware. In this case it is an advantage to include leading zeros for hexadecimal representations of register data for keeping track on the bitwidth.

So instead of passing data argument as 0x1 for a 32bit wide register, I would like to be able to pass it as 0x00000001.

This is not allowed on the tag cxxopts which we are using. Is there a reason that this is not allowed?

I did a little experimentation on the code and found that this is bound by the regular expression which you are using for matching integer options. Originally this is:

cxxopts.hpp:431
namespace
{
  std::basic_regex<char> integer_pattern
    ("(-)?(0x)?([1-9a-zA-Z][0-9a-zA-Z]*)|(0)");
}

But by changing this to 

namespace
{
  std::basic_regex<char> integer_pattern
    ("(-)?(0x)?([0-9a-zA-Z][0-9a-zA-Z]*)|(0)");
}

My problem was solved. Is this a suitable solution - or am I missing the bigger picture here? 

Just out of curiousity: Why is a-z included in a integer pattern and not just a-f?

Thank you for a nice and efficient lib

**Comment by jarro2783** [comment]
That seems reasonable. I think `g-z` were included because you might want integers of other bases. Although I can't remember off the top of my head how all that is handled. I would have to look at the tests to see what it is expected to do.

**Comment by grinder213** [comment]
Thanks for swift responce. I tried to add the follwing patch to a branch of your master code:

diff --git a/include/cxxopts.hpp b/include/cxxopts.hpp
index 58f30aa..25659ae 100644
--- a/include/cxxopts.hpp
+++ b/include/cxxopts.hpp
@@ -442,7 +442,7 @@ namespace cxxopts
     namespace
     {
       std::basic_regex<char> integer_pattern
-        ("(-)?(0x)?([1-9a-zA-Z][0-9a-zA-Z]*)|((0x)?0)");
+        ("(-)?(0x)?([0-9a-fA-F][0-9a-fA-F]*)|((0x)?0)");
       std::basic_regex<char> truthy_pattern
         ("(t|T)(rue)?");
       std::basic_regex<char> falsy_pattern

When ran the tests with this patch all passed with no problems. Let me know if you would like a pull-request to for this.

**Comment by jarro2783** [comment]
That looks good. If you can write a test for it then that would be great too.
