### ISSUE TITLE
.as<T> fails if the option is given but empty

### ISSUE THREAD

**Issue by patrikhuber** [jarro2783/cxxopts#103]
Hi!

Maybe I am missing something here, but I've looked through the readme, example, wiki, and the issues, and couldn't find anything.
If I do this: 
```
std::string input_file;
options.add_options().("i,input", "Input", cxxopts::value(input_file));
```
and then I call the program with `-i` (with the option, but without giving a string), then I'm getting a crash (run-time error).
Likewise, if I do:
```
options.add_options().("i,input", "Input", cxxopts::value<string>());
const auto result = options.parse(argc, argv);
std::string input_file;
if (result.count("input"))
    {
        input_file = result["input"].as<string>();
    }
```
it crashes as well - obviously, because it tries to access a string that is not there.

This kind of seems like a design flaw to me, but I am pretty sure that I just haven't figured out yet how to do this properly. I am surprised though to not find the solution in the readme or an example, or people already asking this in another issue.

Am I just blind or am I not seeing the obvious?

Thanks! :-)

**Comment by jarro2783** [comment]
What sort of a crash is it? If it's throwing an exception then that's fine. It's generally expected that you wrap your argument processing code in a `try` `catch`. That is possibly not so well documented (if at all), which I can definitely fix.

If it is giving you a segmentation fault then that is a bug.

**Comment by patrikhuber** [comment]
Ah, of course. That's it. That was the bit that was missing..... :-)

I think a sentence about that in the readme or wiki would definitely help. But maybe that's just me, since nobody seemed to have run into that before!

Thank you very much for the help and quick reply!
