### ISSUE TITLE
Incorrect behavior when implicit value is present.

### ISSUE THREAD

**Issue by kpyzhov** [jarro2783/cxxopts#104]
Hi there,
Here is my small test:
```
#include "cxxopts.hpp"

int main(int argc, const char* argv[])
{
    try {
        cxxopts::Options opts("Options");
        opts.add_options()
            ("test", "", cxxopts::value<std::string>()->implicit_value("IMPLICIT"));

        auto result = opts.parse(argc, argv);
        if (result.count("test")) {
            std::cout << result["test"].as<std::string>();
        }
    }
    catch (const cxxopts::OptionException& e) {
        std::cout << "Error parsing options: " << e.what() << std::endl;
        exit(1);
    }
    return 0;
}
```
If I specify the option value with '=', it works fine:
```
C:\DEV\work\cxxopts\Debug>cxxopts.exe --test=Value
Value
```
However, if I separate the option and its value with space, it gets the implicit value for some reason:
```
C:\DEV\work\cxxopts\Debug>cxxopts.exe --test Value
IMPLICIT
```
Thanks!
-- Konstantin.

**Comment by jarro2783** [comment]
That's actually expected. I'll have a look at the history of this and the implicit value handling logic to see if there is a good reason for that, and if I can do anything to change it.

Although I think the reasoning is roughly that an option with an implicit value is intended to generally not have arguments. This would allow users to use it as a boolean, but not have a boolean argument, and to override it if they wanted to. The main difficulty is that it isn't obvious whether the next argument should be part of the option or not. I vaguely recall another issue where someone wasn't expecting an option to swallow up a positional parameter that followed.

The other thing is that booleans are actually implemented with `implicit_values("true")`.

**Comment by jarro2783** [comment]
This was changed in abe9ebd6b4084d576ceb79904c94ef8c9c0e6c56.

**Comment by kpyzhov** [comment]
Ok, makes sense. Thanks!
