### ISSUE TITLE
Request: New release with recent fixes

### ISSUE THREAD

**Issue by pluehne** [jarro2783/cxxopts#108]
Hi @jarro2783! I’m linking against cxxopts 2.0.0 in my own project and stumbled upon bug #84, which you kindly fixed with abe9ebd6b4084d576ceb79904c94ef8c9c0e6c56. Thanks a lot :smile:!

I was wondering if you already have plans for a new release? It would be great if I could have a dependency against cxxopts 2.0.1 (or 2.1.0 or whatever the next release will be), because right now, I’ve fixed the cxxopts version to commit abe9ebd6b4084d576ceb79904c94ef8c9c0e6c56, and that is not so nice :slightly_smiling_face:.

(And sorry for opening a full issue for my release request, but I didn’t find a public chat where to ask.)

**Comment by jarro2783** [comment]
I'll do a release soon. There have been several bug fixes recently, I think it's probably time for a version bump.

**Comment by pluehne** [comment]
@jarro2783: Great, that sounds like a good idea :smile:!

**Comment by pluehne** [comment]
@jarro2783: Thanks for publishing 2.1.0!
