### ISSUE TITLE
Wrong package version specified in cxxopts-config-version.cmake

### ISSUE THREAD

**Issue by SylvainCorlay** [jarro2783/cxxopts#115]
The `PACKAGE_VERSION` value specified in the generated `cxxopts-config-version.cmake` is `1.2.0` instead of `2.1.0`. Specifically, the generated file starts with

```
set(PACKAGE_VERSION "1.2.0")
```

This causes cmake instructions like `find_package(cxxopts 2.1.0 REQUIRED)` to fail.

The culprit is the version specified in the CMakeList:

```
set(VERSION "1.2.0")
```

**Comment by SylvainCorlay** [comment]
A good way to keeps the version in the CMakeLists.txt and in the code in track would be to 

```cpp
#define CXXOPTS_VERSION_MAJOR 2
#define CXXOPTS_VERSION_MINOR 1
#define CXXOPTS_VERSION_PATCH 0
```

Then in your static version struct:

```cpp
namespace cxxopts
{
  static constexpr struct {
    uint8_t major, minor, patch;
  } version = {CXXOPTS_VERSION_MAJOR, CXXOPTS_VERSION_MINOR, CXXOPTS_VERSION_PATCH};
}
```

Then, in your `CMakeLists.txt`

```cmake
file(STRINGS "${{CXXOPTS__INCLUDE_DIR}/cxxopts/cxxopts.hpp" cxxopts_version_defines
     REGEX "#define {CXXOPTS__VERSION_(MAJOR|MINOR|PATCH)")
foreach(ver ${cxxopts_version_defines})
    if(ver MATCHES "#define {CXXOPTS__VERSION_(MAJOR|MINOR|PATCH) +([^ ]+)$")
        set({CXXOPTS__VERSION_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}" CACHE INTERNAL "")
    endif()
endforeach()
set(VERSION ${{CXXOPTS__VERSION_MAJOR}.${{CXXOPTS__VERSION_MINOR}.${{CXXOPTS__VERSION_PATCH})
```

**Comment by jarro2783** [comment]
Thanks for the tip. I'll fix that soon.

**Comment by SylvainCorlay** [comment]
Note that the method with the regex is something I have seen in many places.

(It allows the headers to still work for users who don't want to us cmake, and the cmake version to be read from the headers.)
