### ISSUE TITLE
Example to make options like git clone **** --recursive

### ISSUE THREAD

**Issue by saedrna** [jarro2783/cxxopts#119]
Hi,

For many console applications, it is better to organize the command into different sub commands, such as 
`git clone ` `git push ` `git pull`. For different sub command, we may have different options.

Is it possible to do this in cxxopts? Is there a simple demo to do so？

Thanks,

Han

**Comment by jarro2783** [comment]
There is nothing built in to support that. But you could use positional arguments, although the ordering of positional arguments and option arguments would get lost.

So just by doing `options.parse_positional("positional")`, you will get all the non `--` arguments in order. But something like `git --recursive clone` would not be distinguishable from `git clone --recursive`, and the former should probably be an error.

**Comment by saedrna** [comment]
Thanks, I got the idea
