### ISSUE TITLE
Missing tag and release for v2.1.1

### ISSUE THREAD

**Issue by FlorianFranzen** [jarro2783/cxxopts#122]
The latest available release still requires a const argv and the Readme even recommend you to use releases instead of the master branch.

**Comment by jarro2783** [comment]
I'll make a release soon. I've had a few other things to do recently. I'll find some time and finish off the last few issues.

**Comment by jarro2783** [comment]
Actually I just realised that I missed a tag for that release, which is what you were asking. I've pushed a tag.
