### ISSUE TITLE
How to model this use case with cxxopts

### ISSUE THREAD

**Issue by PuneetKohli** [jarro2783/cxxopts#130]
Hi, I have a function which needs to be called like this:-

**Regular mode:-**
`./function -T 1 -K secret -A -D Alice -F file`

**Log mode:-**
`./function -B batch_file`

I can check if all my arguments for regular mode are present by doing something like this..
```
if (result.count("T") == 1 &&
			result.count("F") == 1 &&
			result.count("K") == 1 &&
			(result.count("A") || result.count("L")) == 1 &&
			(result.count("D") || result.count("N")) == 1) { ... } 
```

I am unsure how to also allow my function to take a -B argument, and make sure no other arguments are present?

**Comment by MikeGitb** [comment]
.maybe I'm missing something,  but this seems straight forward:

Check for the presence of B first. If it is present check that the other options are absent and run in log mode. If it is absent, check that the other options are present  and run in regular mode.

**Comment by jarro2783** [comment]
`cxxopts` tries to keep things simple by not supporting logic like that. It will parse all your arguments and that's it. It's up to you to work out if your arguments make sense together.
