### ISSUE TITLE
cxxopts::ParseResult returned by value is broken

### ISSUE THREAD

**Issue by gchoinka** [jarro2783/cxxopts#132]
Thanks for the nice lib,

here is an example https://wandbox.org/permlink/qp0geTxEPm6Ldjy3
```cpp
#include <string>
#include <iostream>

//commit 7c468aaf68206f0f05fcf6c436ed274da138bdbc
#include "cxxopts.hpp"


cxxopts::ParseResult handleCLI(int argc, char ** argv){
  cxxopts::Options options("testapp", "");
  options.allow_unrecognised_options().add_options()
  ("o,outfile", "File name", cxxopts::value<std::string>());
  auto cliArgs = options.parse(argc, argv);
  if (cliArgs.count("outfile")) {
    std::cout << "found " << cliArgs["outfile"].as<std::string>() << "\n";
  }
  return cliArgs;
}

int main(int argc, char ** argv){
    auto cliArgs = handleCLI(argc, argv);
    if (!cliArgs.count("outfile")) {
       std::cout << "strange\n";
    }
}
```

the output is
```
found/dev/null
strange
```

i've also had a look in gdb on mains cliArgs and the object is in an invalid state

**Comment by jarro2783** [comment]
A `ParseResult` object can't leave the scope of the `Options` that it was created from because it holds references to the original object.

**Comment by gchoinka** [comment]
So there is a dependency, I would then recommend to share the data in shared_ptr between the objects, or make ParseResult uncopyable/unmovable (it will not avoid every misuse, but at least avoid this case)

**Comment by jarro2783** [comment]
It needs to be at least moved to return it from `Options::parse`, so that doesn't work.

I will look at whether I can implement this in a better way.
