### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by diekhans** [jarro2783/cxxopts#143]
instruction on building are weak (what is  ${CXXOPTS_DIR} for the non-cmake experts. ??).  make test at root directoruy generates 
`
Test project /cluster/home/markd/compbio/compartiveGenomics/projs/hal/src/cli/cxxopts-2.1.1
No tests were found!!!
`

**Comment by jarro2783** [comment]
I'll take a look at the instructions and see if I can make some improvements. Which instructions are you looking at specifically?

**Comment by jarro2783** [comment]
I've improved the instructions on `master`. Can you tell me if that is sufficient?

**Comment by diekhans** [comment]
the tests still don't run for me.

I do 
cmake $(pwd)
make
make test

and still get the above error

**Comment by jarro2783** [comment]
I forgot that there is a flag that has to be enabled for the tests. I'll fix the instructions again.

**Comment by diekhans** [comment]
Seems like it would be fine to just always compile the tests.

I now get the failure:

`1/3 Test #1: options ..........................***Exception: Child aborted  0.01 sec
`

gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)
