### ISSUE TITLE
Using shortened specification (-f=value) neither works nor throws an error. 

### ISSUE THREAD

**Issue by mrzzzrm** [jarro2783/cxxopts#145]
Pretty much the title. Calling this program:

```c++
#include <iostream>

#include "cxxopts.hpp"

int main(int argc, char * argv[]) {
  cxxopts::Options options("MyProgram", "One line description of MyProgram");

  options.add_options()
  ("f,file", "File name", cxxopts::value<std::string>())
  ;

  auto result = options.parse(argc, argv);
  std::cout << "Yo " << result["f"].as<std::string>() << std::endl;

  return 0;
}
```

Like so: `./main -f=Hello` segfaults when trying to call `as<std::string>()`. Would it be possible to either parse this correctly or throw an error if an option is specified like so?

**Comment by dibdidib** [comment]
Look at "Quick Start" at the very beginning of the docs. This section tells us that --long=description works, but does not promise that -l=description will work. 

So call as:

`./main -file=Hello

**Comment by mrzzzrm** [comment]
I am aware of that. However, given that `-l Hello`, `--long=Hello` and `--long Hello` all work, an unsuspecting *user* of my program might infer that `-l=Hello` works as well and might call the program like that. Now, of course, the program will run with different options than the user thinks it does, which can lead to confusing situations. 

(In our particular case we were running a benchmark application, thinking we had a certain performance-related option enabled, but it was actually disabled because we specified it with `-l=Hello`. Now of course the resulting numbers were misleading, which could have easily been avoided if cxxopts had either processed `-l=Hello` normally or would have *at least* thrown an error that there was a program argument that it couldn't/didn't parse.)

**Comment by mrzzzrm** [comment]
Or in other words: There should be no necessity for the users of my program to study the "Quick Start" section of the library that I happened to use to parse command line arguments.

**Comment by jarro2783** [comment]
I agree that some improvements can be made. It doesn't see `-f=value` as an option at all, so it is just treated as positional parameter. If I'm going to recognise it as something so that I can throw an exception, then I might as well allow the value as well.

As far as the segfault, that's because the option was never provided. So you should be checking first that the option was provided with `result.count("f")`.

**Comment by mrzzzrm** [comment]
Thanks a bunch! Do you have any plans for a release anytime soon? Or would you encourage using the master?

**Comment by jarro2783** [comment]
`master` should be stable enough. I have a few bugs to fix so a release might be a few weeks away.
