### ISSUE TITLE
Signed/unsigned mismatch at line 569 in cxxopts.hpp

### ISSUE THREAD

**Issue by stigrs** [jarro2783/cxxopts#147]
A signed/unsigned mismatch compiler warning is raised at line 569 in cxxopts.hpp when compiling with Visual Studio 2017 and the /W4 warning level.

**Comment by jarro2783** [comment]
Can you give some more details, it will probably only be for some specific template instantiation. Which commit is it on?

I have a few issues for this code, it seems like some compilers don't like my attempts at handling numbers that are technically out of bounds at compile time.

**Comment by stigrs** [comment]
I'm pulling the latest commit. The following example code gives the error:

`
#ifdef _MSC_VER
//#pragma warning(push)
//#pragma warning(disable : 4018 4267) // caused by cxxopts.hpp
#endif

#include <cxxopts.hpp>
#include <iostream>
#include <string>

#ifdef _MSC_VER
//#pragma warning(pop)
#endif

int main(int argc, char* argv[])
{
    // clang-format off
    cxxopts::Options options(argv[0], "Calculate van der Waals interaction");
    options.add_options()
        ("h,help", "display help message")
        ("f,file", "input file", cxxopts::value<std::string>());
    // clang-format on

    auto args = options.parse(argc, argv);

    std::string file = "filename";

    if (args.count("help")) {
        std::cout << options.help({"", "Group"}) << '\n';
        return 0;
    }
    if (args.count("file")) {
        file = args["file"].as<std::string>();
    }
    else {
        std::cerr << options.help({"", "Group"}) << '\n';
        return 1;
    }
    std::cout << file << '\n';
}
`

**Comment by JonnyPtn** [comment]
This is actually fixed in the latest revision, where "digit" now matches the template type. You can close this
