### ISSUE TITLE
'conversion from size_t to US, possible losss of data' warning at line 574 in cxxopts.hpp

### ISSUE THREAD

**Issue by stigrs** [jarro2783/cxxopts#148]
A 'conversion from size_t to US, possible loss of data' compiler warning is raised at line 574 in cxxopts.hpp when compiling with Visual Studio 2017 and the /W4 warning level.

**Comment by jarro2783** [comment]
Which commit is this for?

**Comment by JonnyPtn** [comment]
I get this on v2.1.2

**Comment by JonnyPtn** [comment]
This is actually fixed in the latest revision, where "digit" now matches the template type. You can close this
