### ISSUE TITLE
Hide options from help.

### ISSUE THREAD

**Issue by dagoodma** [jarro2783/cxxopts#16]
I don't see a way of hiding an option from appearing when help() is called. I would like to use this for my positional arguments. Is it difficult to add?

**Comment by jarro2783** [comment]
No this isn't possible at the moment. It shouldn't be too hard to add.

**Comment by jarro2783** [comment]
Actually one way to do it would be to put the hidden options in a separate group, and then only show the groups that you want to. Is this a sufficient solution to your problem?

**Comment by dagoodma** [comment]
Yes good idea! I will try this now and let you know how it goes.

**Comment by jarro2783** [comment]
I have updated the readme to mention this.
