### ISSUE TITLE
If it allows the option to appear multiple times, it should also remember all its values

### ISSUE THREAD

**Issue by yurivict** [jarro2783/cxxopts#161]
There is the ```count()``` function, which means that it allows the option to appear multiple times, but ```as()``` only returns the latest value, which means that the previous values are lost.

It useful to specify the same option several times with different values, so ```cxxopts``` should remember all values.

**Comment by v00d00** [comment]
Yep. Use a vector.

**Comment by jarro2783** [comment]
You need to use a vector of your value type instead of just a single value.

**Comment by yurivict** [comment]
Thank you.
