### ISSUE TITLE
Return value of KeyValue::value()

### ISSUE THREAD

**Issue by paucazou** [jarro2783/cxxopts#166]
Hello,

not sure it is a typo, but inside the definition of KeyValue, line 1092, the return value of KeyValue::value() is a copy and not a reference to m_value.
I find this strange since the return value of KeyValue::key() is a reference to m_key (line 1086).

Sorry if it is intentional (but what is the purpose then ?)
Thanks.

**Comment by jarro2783** [comment]
Yes I'm pretty sure that's incorrect.
