### ISSUE TITLE
std::vector of strings isn't initialized during parsing

### ISSUE THREAD

**Issue by Anton-V-K** [jarro2783/cxxopts#169]
Given the following code fragment:
```
cxxopts::Options options(argv[0], "Tool");
std::vector<std::string> wildcards;
options.add_options()
    ("wildcards", "Which files to process", cxxopts::value<std::vector<std::string>>(wildcards))
    ;
options.parse_positional({"wildcard"});
try
{
    auto result = options.parse(argc, argv);
   ...
```
I expected that `wildcards` would get a list of string, but this doesn't happen. The code compiles fine, but `wildcards` stay empty.
Such case isn't covered by the example, so I'm wondering is it supposed to work this way (whether this is a bug)?

**Comment by jarro2783** [comment]
That should work. I'll take a look.

**Comment by jarro2783** [comment]
The example uses it with the parameter `positional`. Can you give me a complete piece of code that reproduces the problem?

**Comment by Anton-V-K** [comment]
Thanks for looking into this.
Actually there was a typo in my code `options.parse_positional({"wildcards"});` - trailing `s` was missing in `wildcards`, and the name didn't match the parameter "declaration".
And it works as expected.

**Comment by jarro2783** [comment]
It might be worth throwing an exception if the user tries to set positional arguments for an option that doesn't exist.
