### ISSUE TITLE
Count duplicate option occurences

### ISSUE THREAD

**Issue by dagoodma** [jarro2783/cxxopts#17]
Hello,

I was wondering if there is a way to specify duplicate flags and have cxxopts count the occurrences. For instance, I would like to have a verbose options with increasing levels of verbosity so that I can give: -v, -vv, -vvv, -v -v -v, ect.. and calling options.count("verbose") should return 1, 2, 3, and 3 respectively.

This behavior is similar to the argument parser in python (see the 'count' action): https://docs.python.org/3/library/argparse.html#action

**Comment by dagoodma** [comment]
A temporary work around for implementing this behavior is by passing an argument after -v to specify verbosity level. For example:

    ./myProgram -v 3

The only issue with this is that an argument MUST be specified after -v, so

    ./myProgram -v
will throw an error due to a missing argument.

**Comment by jarro2783** [comment]
This works already. If you make v a boolean option, the number of times it appears will be counted. I think for any option the number of times it appears will be counted, but for single value options only the last option will be saved.
