### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by pcorbineau** [jarro2783/cxxopts#175]
The following line can never be reached :
https://github.com/jarro2783/cxxopts/blob/e34676f73e49eeff30cb101f1c5ba8806fbe6773/include/cxxopts.hpp#L1666

On VS2019 it throws a warning C4702 : unreachable code

As I build my project with treat warning as error for release, I can't build it.

Regards

**Comment by jarro2783** [comment]
Ah so it is. I'll fix that.
