### ISSUE TITLE
Add handling of -- to end options

### ISSUE THREAD

**Issue by martinmoene** [jarro2783/cxxopts#18]
Although `prog -a -b -` works to specify `-` as the first positional argument (or *input* in the [example](https://github.com/jarro2783/cxxopts/blob/master/src/example.cpp), being able to end the options explicitly via `--` has its place, e.g.:

```
prog -a -b -- -silly-filename
```
See also [Guideline 10](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02) of Posix Utility Conventions, [12.1 Utility Argument Syntax](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html):

>Guideline 10:
>    The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.

**Comment by jarro2783** [comment]
Added in 3ce8cbd1aebaba44873bd9aa4a7a81661dd36715.

**Comment by martinmoene** [comment]
Thanks!
