### ISSUE TITLE
Why is `.as<T>` necessary?

### ISSUE THREAD

**Issue by llamasoft** [jarro2783/cxxopts#184]
For example, from the [Quick Start](https://github.com/jarro2783/cxxopts/wiki/Quick-start) page, the value for the "file" option is retrieved with `options["file"].as<std::string>();`.  
Why is the type necessary when it was already defined during `add_options()`?  Shouldn't it use the type specified there instead?  Or is this caused by a language limitation?

**Comment by jarro2783** [comment]
The type does have to be the same, otherwise an exception will be thrown. But the type still has to be specified, because the compiler can't know at compile time what the result of looking up `options["name"]` will be.
