### ISSUE TITLE
can cxxopts parse command tokens?

### ISSUE THREAD

**Issue by yurivict** [jarro2783/cxxopts#187]
I couldn't find this information in the documentation or examples.

I need to parse options, but it should be able to recognize command tokens, for example:

1. command token followed by arguments:
> myprog cmd1 --argument1 arg1 --argument2 arg2 ...

2. command token preceded with options and followed by arguments:
> myprog --option1 opt1 --option2 opt2 cmd2 arg1 --option2 arg2 ...

There should be only one or zero command tokens allowed.

--------

Please consider expanding documentation (or README), because the above situation isn't covered in README.

**Comment by jarro2783** [comment]
It can't parse commands options like that. It seems sufficient to me to only document features that exist, rather than to list a whole bunch of things that it can't do.

**Comment by yurivict** [comment]
Please consider this a feature request then.
You can for example look at what command line does ```docker``` accept, it does process sub-commands, see here for example: https://docs.docker.com/engine/reference/commandline/docker/

-------

Thanks for your answer. Bye.
