### ISSUE TITLE
nested option groups

### ISSUE THREAD

**Issue by amigo421** [jarro2783/cxxopts#19]
does the lib supports nested option groups like boost::program_options? I mean an ability to create a few independent groups of options and use one of them depends of group selection

**Comment by jarro2783** [comment]
Unfortunately the library can't do that. The option groups are only for separating help messages.

I don't think it would be too difficult to add. How much would you like this feature?

**Comment by amigo421** [comment]
Not so much :) I've just tried to understand the idea of "group" term in case of compare with boost program options. Current functionality looks ok for me, the only thing which I'd improve is a building full string of the program syntax

**Comment by jarro2783** [comment]
What do you mean by that last sentence? Can you give an example and I might be able to work on something?

**Comment by amigo421** [comment]
line:1324
String result = "Usage:\n  " + toLocalString(m_program) + " [OPTION...]"

instead of "option..." would be better to show formatted string  with a real parameters .
which can be  extracted from already added options. 
I don't remember where I saw this, possibly in boost program_option, or in Qt parsecommandline class.

**Comment by jarro2783** [comment]
I know of plenty of programs that do it, but I suspect that they are hard coding some required options in the program description. I can't see a sane way to do this since three could be a lot of options, and the library has no way of knowing which options are more important than others.
