### ISSUE TITLE
How to use the default value when the option is not given

### ISSUE THREAD

**Issue by sschleic** [jarro2783/cxxopts#191]
With the following code I set the option port to default 9001:
options.add_options()("p, port", "port where the server is running", cxxopts::value<int>(), "9001");
auto result = options.parse(argc, argv); 
This is fine.
How can I use the default value 9001 later.
I want to do something similar to the following:
if (result.count("port")) { 
//proceed with given port
auto port = result["port"].as<int>();
}
else{
//proceed with given default value
auto port = result["port"].as<int>(); //will raise an error
}
How can I get the default value entered in the option definition?

Best regards
Stephan

**Comment by jarro2783** [comment]
The fourth argument where you have passed `"9001"` is not the default value.

You need to call `default_value` on the `cxxopts::value` object. Then that option will always be present, as in `count` will always return at least 1 and you use it like any other option.

**Comment by sschleic** [comment]
Thanks a lot
