### ISSUE TITLE
Vector option default value duplicated

### ISSUE THREAD

**Issue by leanil** [jarro2783/cxxopts#197]
Hi,
It seems to me like vector option default values were concatenated. Is this intentional?
* set both a short and a long name for a vector valued option
```cpp
    options.add_options()
        ("o,opt", "asd", cxxopts::value<vector<int>>()->default_value("0,1"));
    auto result = options.parse(argc, argv);
    vector<int> v = result["opt"].as<vector<int>>();
    for(int x : v)
        cout << x << ' ';
```
* don't provide any of them at runtime
```
    $ ./a.out 
    0 1 0 1
```
If I set only one name for the option, then I get the expected result. So I guess it detects that both the short and long versions are missing, but adds the default values instead of overwriting.

**Comment by jarro2783** [comment]
That certainly looks wrong. I will have a look at this.
