### ISSUE TITLE
Can you add default values to options (so that they are optional)?

### ISSUE THREAD

**Issue by cossio** [jarro2783/cxxopts#20]
I would like to have an option, that takes a value. But if the option is not given, a default value should be used. Is this possible here?

I know I can check explicitly whether the option was entered via "count". But I was wondering if there was an API dedicated to this?

**Comment by jarro2783** [comment]
See src/example.cpp line 43.

You can specify a default value with the function `Options::default_value`. Note that an option with a default value must have its value specified with --arg=value.

**Comment by jarro2783** [comment]
I don't understand what you mean by an API dedicated to the count function.

**Comment by jarro2783** [comment]
The documentation needs to be made clearer for this.

An option can have both an *implicit* value and a *default* value.

 * Implicit value: when the option is specified with no parameter, it takes the implicit value.
 * Default value: when the option is not specified it is as though it is still present and takes the default.

For example, with `-o` having implicit value `b.def` and default value `a.out`, we get:
    # src/example 
    Output = a.out
    # src/example -o
    Output = b.def
