### ISSUE TITLE
cxxopts does not compile under MSVC 2013

### ISSUE THREAD

**Issue by mansoor2016** [jarro2783/cxxopts#202]
Dev studio 15.6.7 targetting platform toolset v120 (2013) and language standard /std:c++11.

**Comment by v00d00** [comment]
Maybe you should post the error?

**Comment by mansoor2016** [comment]
The errors relate to the use of constexpr variables, noexcept functions and anonymous structs. This functionality was not implemented in the 2013 version of the MSVC compiler. These can either be corrected with hash-defs or it should be listed as an incompatible compiler.

**Comment by cwreynolds** [comment]
As @v00d00 says, it is always helpful to include the exact text of the error.

**Comment by jarro2783** [comment]
Can you post the error so that I can see where the problems are.

**Comment by mansoor2016** [comment]
The errors are not descriptive but they do provide the location. 
`
1>Target ClCompile:
1>  Source.cpp
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(52): error C2143: syntax error : missing ';' before '<class-head>'
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(52): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(329): error C3646: 'noexcept' : unknown override specifier
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(764): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(765) : see reference to class template instantiation 'cxxopts::values::type_is_container<T>' being compiled
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(764): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(770): error C2144: syntax error : 'bool' should be preceded by ';'
1>          c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(771) : see reference to class template instantiation 'cxxopts::values::type_is_container<std::vector<T,std::allocator<_Ty>>>' being compiled
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(770): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(909): error C2886: 'abstract_value<T>' : symbol cannot be used in a member using-declaration
1>          c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(916) : see reference to class template instantiation 'cxxopts::values::standard_value<T>' being compiled
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(995): error C2610: 'cxxopts::OptionDetails::OptionDetails(cxxopts::OptionDetails &&)' : is not a special member function which can be defaulted
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(1079): error C3646: 'noexcept' : unknown override specifier
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(1086): error C3646: 'noexcept' : unknown override specifier
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(1437): error C2144: syntax error : 'int' should be preceded by ';'
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(1437): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(1438): error C2144: syntax error : 'int' should be preceded by ';'
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(1438): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>  c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(1438): error C2086: 'int cxxopts::`anonymous-namespace'::constexpr' : redefinition
1>          c:\users\manam\source\repos\errorsforcxxopts\errorsforcxxopts\cxxopts.hpp(1437) : see declaration of 'cxxopts::`anonymous-namespace'::constexpr'
1>Done building target "ClCompile" in project "ErrorsForCxxopts.vcxproj" -- FAILED.`

**Comment by mansoor2016** [comment]
[cxxopts.hpp.txt](https://github.com/jarro2783/cxxopts/files/3524593/cxxopts.hpp.txt)

This is a version of the header that is compatible with MSVC 2013 (x86 /std:c++11). It hash-defs out the inherited constructor on line 927, but if this were an issue, it would show up at compile time.

**Comment by jarro2783** [comment]
Which version of cxxopts is this for?

**Comment by mansoor2016** [comment]
> Which version of cxxopts is this for?

Relatively recent master branch.

**Comment by jarro2783** [comment]
By the looks of those errors that compiler doesn't even support all of C++11. I could put a note in the readme about features needed, but tracking down every compiler version that doesn't work is not trivial.

**Comment by mansoor2016** [comment]
> By the looks of those errors that compiler doesn't even support all of C++11. I could put a note in the readme about features needed, but tracking down every compiler version that doesn't work is not trivial.

I agree, which is why I suggested noting in the readme that MSVC 2013 was not supported (it is fairly old).
