### ISSUE TITLE
Setting width of helplines by option

### ISSUE THREAD

**Issue by wgahr123** [jarro2783/cxxopts#213]
I had a similiar wish  as @mmanolescu  had in issue #137 *Indentation in help*:

* I use multiline helptexts, which should be set with the right indentation.
* Additionally I want to change the allowed length of lines of help texts.

The following patch to commit https://github.com/jarro2783/cxxopts/commit/073dd3e645fa0c853c3836f3788ca21c39af319d gives us these things.

### Patch

```c++
--- cxxopts.hpp     2019-11-10 19:34:01.295925400 +0000
+++ cxxopts.hpp     2019-11-10 19:38:25.647845500 +0000
@@ -1297,6 +1297,7 @@
     , m_positional_help("positional parameters")
     , m_show_positional(false)
     , m_allow_unrecognised(false)
+    , m_width(76)
     , m_options(std::make_shared<OptionMap>())
     , m_next_positional(m_positional.end())
     {
@@ -1330,6 +1331,13 @@
       return *this;
     }

+    Options&
+      set_width(size_t width)
+    {
+      m_width = width;
+      return *this;
+    }
+
     ParseResult
     parse(int& argc, char**& argv);

@@ -1414,6 +1422,7 @@
     std::string m_positional_help;
     bool m_show_positional;
     bool m_allow_unrecognised;
+    size_t m_width;

     std::shared_ptr<OptionMap> m_options;
     std::vector<std::string> m_positional;
@@ -1540,6 +1549,13 @@

         if (*current == '\n')
         {
+          stringAppend(result, startLine, current + 1);
+          stringAppend(result, std::string(start, ' '));
+          startLine = current + 1;
+          size = 0;
+        }
+        else if (*current == '\0')
+        {
           startLine = current + 1;
           lastSpace = startLine;
         }
@@ -2086,7 +2102,7 @@
   longest = (std::min)(longest, static_cast<size_t>(OPTION_LONGEST));

   //widest allowed description
-  auto allowed = size_t{76} - longest - OPTION_DESC_GAP;
+  auto allowed = m_width - longest - OPTION_DESC_GAP;

   auto fiter = format.begin();
   for (const auto& o : group->second.options)
```

### Example of use (snippet)

```c++
    cxxopts::Options options(argv[0], " - Do something interesting");

    options
      .positional_help("[optional args]")
      .show_positional_help();
      .set_width(120)
      .add_options()
      ("t,timestep", "Set timestep in seconds\nDefault: 1.0", cxxopts::value<double>(timestep))
      ("n,number_of_orbits", "Number of orbits to be computed\nDefault: 3, no limit: 0", cxxopts::value<int>(number_of_orbits))
      ("m,method", "Method for simulation\n"
                   "Method 1: steps with linear simulation\n"
                   "Method 2: steps with quadratic simulation\n"
                   "Method 3: steps with quadratic simulation and average of accelerations (Default)", cxxopts::value<int>(method))
      ("v,view", "Print results in range -val..+val at the perihel, val in seconds of arc\nDefault: 6.0", cxxopts::value<double>(view))
      ("h,help", "Print help")
      ;
```
#### Helptext created by *.set_width(120)*
```
MyProgram.exe - Do something interesting
Usage:
  MyProgram.exe [OPTION...]

  -t, --timestep arg          Set timestep in seconds
                              Default: 1.0
  -n, --number_of_orbits arg  Number of orbits to be computed
                              Default: 3, no limit: 0
  -m, --method arg            Method for simulation
                              Method 1: steps with linear simulation
                              Method 2: steps with quadratic simulation
                              Method 3: steps with quadratic simulation and average of accelerations (Default)
  -v, --view arg              Print results in range -val..+val at the perihel, val in seconds of arc
                              Default: 6.0
  -h, --help                  Print help
```

#### Helptext created by *.set_width(50)*
```
MyProgram.exe - Do something interesting
Usage:
  MyProgram.exe [OPTION...]

  -t, --timestep arg          Set timestep in seconds
                              Default: 1.0
  -n, --number_of_orbits arg  Number of orbits to be computed
                              Default: 3, no limit: 0
  -m, --method arg            Method for simulation
                              Method 1: steps with linear simulation
                              Method 2: steps with quadratic simulation
                              Method 3: steps with quadratic simulation and
                              average of accelerations (Default)
  -v, --view arg              Print results in range -val..+val at the
                              perihel, val in seconds of arc
                              Default: 6.0
  -h, --help                  Print help
```

**Comment by jarro2783** [comment]
Thanks, that looks useful. Can you submit it as a PR?

**Comment by wgahr123** [comment]
Hello,

 

I am pretty busy this time, but In  the next days I will do.

 

I found another issue:

 

inline

String

Options::help_one_group(const std::string& g) const

{

  …  

    //widest allowed description

    auto allowed = size_t{76} - longest - OPTION_DESC_GAP;

 

Now, when longest is too big ( 76 <  longest + OPTION_DESC_GAP), the result is negative.

Unfortunately size_t is unsigned, so the result is a very big number.

The help text is accordingly set without additionally linebreaks.

Because of that nobody has recognized, I think.

To change this is maybe a little academical:

 

  //widest allowed description

  auto allowed = size_t{};

  if (m_width < (longest + OPTION_DESC_GAP + 10))

  {

    allowed = longest + OPTION_DESC_GAP + 10;

  }

  else

  {

    allowed = m_width - longest - OPTION_DESC_GAP;

  }

 

The helpline is truncated but only til friendly 10 chars – otherwise there would be nothing or maybe a loop.

 

A shorter version would be:

 

  //widest allowed description

  auto allowed = longest + OPTION_DESC_GAP + 10;

  if (m_width >= allowed)

  {

    allowed = m_width - longest - OPTION_DESC_GAP;

  }

 

Best regards, Wolfgang

 

 

Von: jarro2783 <notifications@github.com> 
Gesendet: Montag, 11. November 2019 22:25
An: jarro2783/cxxopts <cxxopts@noreply.github.com>
Cc: Wolfgang Gahr <gahrwolfgang@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [jarro2783/cxxopts] Setting width of helplines by option (#213)

 

Thanks, that looks useful. Can you submit it as a PR?

**Comment by K-Wone** [comment]
I'm trying to print a multiline help message with v2.2.0. It seems that `format_description(...)` skipped the `\n` in the description. The simplest way to show it is to modify `example.cpp` like this

```c++
-       ("help", "Print help")
+       ("help", "Print\nhelp")
```

The first line `Print` will be skipped.

Is this a bug or something? Anyway, it has been fixed by this patch.

**Comment by henrik-jensen** [comment]
@wgahr123 , @wgahr123 - Has this been made into a PR yet? Don't show up on the [PR list](https://github.com/jarro2783/cxxopts/pulls)
This is just what I'm looking for.

**Comment by ashlander** [comment]
Hi,

I am making some higher level stuff (https://github.com/ashlander/protoargs)  based on your great project. And I am really missing "\n" or similar support, providing better formatting. I use 2.12 release version right now.

I see there are some changes about multi-line help supports here, but I can't find any signs of it in the repo despite merge commit. Am i correct that it is still not merged even partially (and no release) ?

Thanks

**Comment by wgahr123** [comment]
Because of unicode problems I had to rewrite the change, and added the handling for tabulators. That’s why I took back #213 and it is now #215.

Von: Henrik Jensen <notifications@github.com> 
Gesendet: Sonntag, 5. April 2020 20:21
An: jarro2783/cxxopts <cxxopts@noreply.github.com>
Cc: Wolfgang Gahr <gahrwolfgang@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [jarro2783/cxxopts] Setting width of helplines by option (#213)

 

@wgahr123 <https://github.com/wgahr123>  , @wgahr123 <https://github.com/wgahr123>  - Has this been made into a PR yet? Don't show up on the PR list <https://github.com/jarro2783/cxxopts/pulls> 
This is just what I'm looking for.

**Comment by wgahr123** [comment]
The replacement PR 215 was merged already.
