### ISSUE TITLE
Example src/example.cpp accesses object with expired lifetime

### ISSUE THREAD

**Issue by Muxas** [jarro2783/cxxopts#219]
According to readme: 

> Note that the result of options.parse should only be used as long as the options object that created it is in scope.

But provided example (src/example.cpp) defines options object in a function, that returns result of options.parse to main. Seems like example is invalid. Or information in Readme should be updated.

```
int main(int argc, char* argv[])
{
  auto result = parse(argc, argv);
  auto arguments = result.arguments();
  std::cout << "Saw " << arguments.size() << " arguments" << std::endl;

  return 0;
}
```

**Comment by jarro2783** [comment]
The example is in fact wrong. I am working on a rewrite of this, but I will fix the example for now so that it doesn't use undefined behaviour.
