### ISSUE TITLE
Can I run it without an argument?

### ISSUE THREAD

**Issue by Kaiwind88** [jarro2783/cxxopts#230]
I am trying to run a binary with options like this: the first one does not have an argument but only a value. 

<binary> someDirectory -saveData true

Is it possible? If so, how to set in the code?

Thanks.

**Comment by jarro2783** [comment]
You can use positional arguments for that. You can assign a single value variable to the first positional argument.

**Comment by Kaiwind88** [comment]
Hi Jarro，

Thank you for your reply. I am pretty new to the options and also cpp, so just not quite sure of how to implement it.  Could you provide an example?

Thanks.

**Comment by jarro2783** [comment]
Sure. You would add an argument that takes a string:
```
options.add_options()
  ("f,file", "File name", cxxopts::value<std::string>())
```
then call
```
options.parse_positional({"file"});
```

Then when you call `options.parse`, the first argument without an option name will be parsed into `file`.

**Comment by Kaiwind88** [comment]
Thanks for the example. It works. But the positional argument is still not quite clear to me. 

In readme: 
> options.parse_positional({"first", "second", "last"})
where "last" should be the name of an option with a container type, and the others should have a single value.

For example: `options.parse_positional({"a", "b", "c", "d", "d"})`, do you mean the last one of 'a' 'b', 'c', 'd', ie 'd', should be a container type? Could you elaborate it or provide some examples? 

Thanks.

**Comment by jarro2783** [comment]
You would do something like this:
```
("f,file", "File name", cxxopts::value<std::vector<std::string>>())
```
where the argument type is a vector.

Yes only the last of those should be a container, because the first container type will gobble up the rest of the arguments.
