### ISSUE TITLE
Support not-failing with unknown options

### ISSUE THREAD

**Issue by eyalroz** [jarro2783/cxxopts#239]
Loggers should have a flag which, when set, has them not fail when encountering unknown options, but rather merely collecting them appropriately and making them accessible after parsing. This feature would be independent of whether secondary parsing is supported by the Options class or not.

This is important in particular for the case of computational work being necessary, using the values of some command-line arguments, to determine a secondary set of command-line-settable options (e.g. by reading from some file or loading a dyanmic library and so on.)

**Comment by rtlayzell** [comment]
Seconded. Parsing an unknown option is not exceptional behavior. I would like to log the fact that a user has passed an unknown option and continue with the application. Right now that's quite difficult (impossible without parsing and removing the offending myself). 

I would also like to ask if we could get the name of the offending option in the error as I would like to form my own message as opposed to just spitting out `what()`. I could probably make a pull request if that would suit.

**Comment by eyalroz** [comment]
@rtlayzell : I think your second paragraph would be a separate issue than making it not-an-error. Of course if you got the unrecognized options and their values, you could then do whatever error handling you like on your own. I would even go as far as saying that this should be the default (separation of concerns - parsing arguments and handling errors), but that's probably too radical of a change.

**Comment by jarro2783** [comment]
See `Options::allow_unrecognised_options`.

**Comment by rtlayzell** [comment]
@jarro2783 that's not quite what I (we?) are looking for. I don't want to ignore unknown options, I want to handle them as part of the parse result. You could introduce a non-breaking change in the `cxxopts::ParseResult` class that just returns a list of any unrecognised options. e.g.

```
auto results = opts.parse(argc, argv);
for (auto opt : results.unrecognised()) {
    std::cerr << "error: option \'" << opt.key() << "\' is not recognised.. blah.." << std::endl;
}
```

*Side note* I had to upgrade to v2.2 and noticed that `cxxopts::Options::parse` no longer accepts `const` references(?) I was curious as to why the parse method needs to mutate the input arguments themselves?

**Comment by jarro2783** [comment]
Ignoring them means they are left in the arguments array, so they are not completely lost. Although this pretty much only works if you don't have positional arguments consumed into another container.

The library mutates the input array and count to leave behind anything not recognised. This is a bit tricky though because you can never tell if an unrecognised option takes an argument or not, so if you consume positional arguments then you might lose some information.

Yeah returning an array of unrecognised arguments is a reasonable way to solve that, and I have plans at some point to fix this to not mutate the input.

**Comment by rtlayzell** [comment]
I see your point, I think it reasonable to assume that any unrecognised option is supplied without argument, such that `program --unrecognised value a` equates to a single named option and two positional arguments. I wouldn't try to guess if the option was intended to be supplied with arguments or not. It is the users error and any program that accepts positional arguments should reject the meant-to-be-an-argument-but-parsed-as-positional if it isn't valid.

**Comment by eyalroz** [comment]
@rtlayzell :
> I think it reasonable to assume that any unrecognised option is supplied without argument, such that program --unrecognised value a equates to a single named option and two positional arguments.

It is not reasonable - just like it's not reasonable for options we do know about.

@jarro2783 :
`allow_unrecognized_options()` that's already better than what I had assumed was the case, but:

1. It's essentially undocumented... enough for both of us to have missed it. I know now that there's an example using this feature, but that's not nearly enough IMHO.
2. I was searching the code for `m_allow_unrecognised`, the flag that calling the method sets, and [couldn't find its uses](https://github.com/jarro2783/cxxopts/search?q=m_allow_unrecognised&unscoped_q=m_allow_unrecognised)...
3. Like you said, things could use further improvement. Specifically, what happens if I add options to the parser, after parsing, and then give it the remaining, unprocessed arguments? It should ideally be the case that the final result will be as though I had added all the options from the get-go.

**Comment by rtlayzell** [comment]
@eyalroz What do you propose is done about it then? You cannot determine whether or not an unrecognised option was intended to be supplied with N arguments, unless you use the `--option=value` syntax. The way I see it, you can do one of two things: 

a) Absorb all positional text that comes after an unrecognised flag and assume that they were supplied as arguments to unrecognised option.

b) Ignore subsequent positional text that comes after the unrecognised option and assume that the positional text was intended as such.

So those are the choices, and personally I prefer b's approach.

**Comment by eyalroz** [comment]
>  unless you use the --option=value syntax

But that's what you're supposed to do anyway. `--option argument-of-option` is less-standard, I would say. So option (c) on your list is:

c) Parse unknown options assuming `-` options are single-character flags, possibly with an joint argument following without a space; `--` options are options no additional arguments or with a single additional argument if specified with a `=`, and everything remaining are positional arguments.

**Comment by rtlayzell** [comment]
@eyalroz I agree, if an unknown option is parsed with an `=`, as in `--option=value` then `value` should be parsed as an argument of `option`. Without the `=` it should be assumed that any positional text following are positional arguments. I'm not sure I understand what you're trying to say about single-character flags though.
