### ISSUE TITLE
Will there be a new release soon?

### ISSUE THREAD

**Issue by beojan** [jarro2783/cxxopts#241]
2.2.0 was release over a year ago, while the last commit was last month.

**Comment by jarro2783** [comment]
I have some plans for a few improvements, but my next release will likely be a major change to fix some of the bigger issues.
It's a matter of finding enough time to do that, but I can probably get that done within a couple of maths.

**Comment by beojan** [comment]
The README contains a note that you should usually use a tagged release version. Is this still up to date then?

**Comment by jarro2783** [comment]
Yes. Master should usually work, but can contain breaking changes that you don't expect. So the tags will always be the most stable thing that you can use.

**Comment by jarro2783** [comment]
Released v2.2.1 just now.
