### ISSUE TITLE
Error C2679: binary '>>': no operator found which takes a right-hand operand of type 'T' (or there is no acceptable conversion)

### ISSUE THREAD

**Issue by ThisIs0xBC** [jarro2783/cxxopts#248]
Getting this error (Error C2679: binary '>>': no operator found which takes a right-hand operand of type 'T' (or there is no acceptable conversion)) on line 648 of cxxopts.h.

Using MSVC in Visual Studio with Platform Toolset v142, and Windows SDK version 10.0

Am I being stupid and have I done something wrong? Or is this an actual issue?

**Comment by john-h-k** [comment]
Include `#include <iostream>` above your include

**Comment by ThisIs0xBC** [comment]
That would do it, I'm a bit slow today lol :(
