### ISSUE TITLE
PR 250 broke support for `int main(int, char**)`

### ISSUE THREAD

**Issue by cstratopoulos** [jarro2783/cxxopts#252]
See https://godbolt.org/z/5zvaYn -- due to the changes from #250 calling `options.parse` with `char**` fails as `char**` (i.e., array of pointer to `char`) cannot bind to lvalue-ref to `const char**` (i.e., array of pointer to `char const`)

See [SO](https://stackoverflow.com/questions/2108192/what-are-the-valid-signatures-for-cs-main-function) for a discussion on valid ways to spell `main`, and in particular [this comment](https://stackoverflow.com/questions/2108192/what-are-the-valid-signatures-for-cs-main-function#comment38179126_2108208) regarding the use of array of `char const*`. 

In practice, I suspect that
```
char const** argv
char const* argv[]
```
are both widely or universally supported. However, per the discussions above, strict conformance with the standard requires
```
char** argv
char* argv[]
```
or equivalent.

I notice that, e.g., https://github.com/jarro2783/cxxopts/blob/master/src/example.cpp#L163 uses the `char const*` array signature. I haven't audited all the other test code, but this might be a good check to add for CI as it would guarantee, in particular, that https://github.com/jarro2783/cxxopts#example would compile

As a side note I have also wished to be able to support the use case described [here](https://github.com/jarro2783/cxxopts/pull/250#issuecomment-670563487) with unit tests that put program args in an array. Maybe this just means the way forward involves overloading some function signatures rather than the
```diff
-      int&, char**&);
+      int&, const char**&);
```
approach

**Comment by kjetand** [comment]
The initial commit in https://github.com/jarro2783/cxxopts/pull/250#issuecomment-670563487 made an overload such that both `char*` and `const char*` was supported. For backwards compatability, probably both should be supported as you describe.

From an API point of view, the only correct type should probably be `const char* const*`, because there is no reason for cxxopts to modify the input at all (except I see in unit tests that this feature is used to assert certain things).

**Comment by jarro2783** [comment]
Thanks for pointing that out. In fact the initial commit was correct with the const cast, I just didn't test it properly.

The reason that this will never work is explained here https://stackoverflow.com/questions/7016098/implicit-conversion-from-char-to-const-char

I know that cxxopts doesn't write into that array, so a const cast is actually correct. I'm just working on a fix with some tests for different const cases to improve the flexibility.

**Comment by sheerluck** [comment]
Somehow [997577b](https://github.com/jarro2783/cxxopts/commit/997577bef28010420bfa279a324cc057fc2d69e7) still not in the master branch yet

**Comment by jarro2783** [comment]
I think I forgot to merge that. I'm working on another change that is very close to being ready that will fix all of this properly. You can see the changes in https://github.com/jarro2783/cxxopts/tree/parse_refactor
