### ISSUE TITLE
Allow specifying an argument indicator other than "arg"

### ISSUE THREAD

**Issue by eyalroz** [jarro2783/cxxopts#253]
If we have an option which takes an optional argument, and print the usage info, we get:
```
    -i, --input arg       Read input from file
```
what if I want to print "filename" instead of "arg", to indicate that the argument is a filename? cxxopts should let me specify such this indicator when I add the option; like we can specify a default_value.

**Comment by jarro2783** [comment]
Thanks for looking into this everyone.

**Comment by Enissay** [comment]
> Looking over the code for a few minutes, it seems to me that this behavior is already supported:
> 
> `Options::add_option` allows you, among other things to specify an `arg_help` string. And this seems to be doing exactly what you are asking for.
> 
> ```
> [I] ➜ ./a.out --help
>  - example command line options
> Usage:
>   ./a.out [OPTION...] [optional args]
> 
>   -a, --apple                   an apple
>   -b, --bob                     Bob
>       --char arg                A character
>   -t, --true                    True (default: true)
>   -f, --file FILE               File
>   -i, --input filename          Input
>   -o, --output [=BIN(=b.def)]   Output file (default: a.out)
>   -x arg                        A short-only option
>       --positional arg          Positional arguments: these are the arguments
>                                 that are entered without an option
>       --long-description        thisisareallylongwordthattakesupthewholelinean
>                                 dcannotbebrokenataspace
>       --help                    Print help
>       --int N                   An integer
>       --float arg               A floating point number
>       --vector arg              A list of doubles
>       --option_that_is_too_long_for_the_help
>                                 A very long option
> 
>  Group options:
>   -c, --compile   compile
>   -d, --drop arg  drop
> ```
> 
> Notice the `filename` after `--input` above. It's the result of providing an explicit `arg_help` as here `("i,input", "Input", cxxopts::value<std::string>(), "filename")`.

I wonder where is the code for this ?
