### ISSUE TITLE
Empty option name on exception throwing

### ISSUE THREAD

**Issue by GregoryIstratov** [jarro2783/cxxopts#255]
The following code:

   options.add_options()
        ("m,model", "Model file", cxxopts::value<std::string>())
        ("i,input", "Input video filename", cxxopts::value<std::string>())
        ("o,output", "Result video filename", cxxopts::value<std::string>())
        ("h,help", "Print usage")
        

    auto result = options.parse(argc, argv)

    a.model = result["model"].as<std::string>()

throwing exception ( as expected ) with empty option name:

` Option '' has no value`

**Comment by pag** [comment]
Can you please merge this? It's really annoying to have no default value in the exception.

**Comment by jarro2783** [comment]
Done
