### ISSUE TITLE
How to easily enter multiple file names?

### ISSUE THREAD

**Issue by K-JW** [jarro2783/cxxopts#261]
Hello developer, 

First, thank you for contributing such a great library. Now I have a simple question. 

Sometimes we need to pass in multiple filenames to a program, for example:

```bash
./exe -t figure -o ./DIR *.jpg
```
In the [cmdline](https://github.com/tanakh/cmdline) library, we can set

```c++
args.footer("filenames...");
``` 
and get all filenames to use

```c++
for (size_t i = 0; i < args.rest().size(); i++) {
     file_name_vec.emplace_back(args.rest()[i]);
}
```

I would like to ask how to implement similar functions in this library? 

Thanks!

**Comment by jarro2783** [comment]
You can either allow unrecognised options as described here: https://github.com/jarro2783/cxxopts#unrecognised-arguments or you can make a container option: https://github.com/jarro2783/cxxopts#options-specified-multiple-times and then specify positional arguments to be parsed into that container: https://github.com/jarro2783/cxxopts#positional-arguments

**Comment by K-JW** [comment]
Indeed, this is a way. Thanks!
