### ISSUE TITLE
potential null pointer dereference error with gcc-10. (gcc bug ?)

### ISSUE THREAD

**Issue by bsergean** [jarro2783/cxxopts#263]
```
/xxx/build/_deps/cxxopts-src/include/cxxopts.hpp: In member function ‘size_t cxxopts::ParseResult::count(const string&) const’:
/xxx/build/_deps/cxxopts-src/include/cxxopts.hpp:1027:14: warning: potential null pointer dereference [-Wnull-dereference]
 1027 |       return m_count;
      |              ^~~~~~~
```

The code is:

```
    size_t
    count() const
    {
      return m_count;
    }

...
    // m_count being a member variable
    size_t m_count = 0;
```

I don't really get it, but reporting just in case. This is one of the few places where an integer is initialized like that, maybe initializing it in a constructor would get rid of the problem.

**Comment by jarro2783** [comment]
This sounds like a bug in GCC, the only potential null pointer there is `this`, but then you would have that problem in _every_ member function. I would hope that GCC is not trying to solve that problem.

**Comment by bsergean** [comment]
Yes that sounds like a bug in gcc. The reason this is getting in my way is that the examples are built by default and so when I include your project through cmake magic things break.

option(CXXOPTS_BUILD_EXAMPLES "Set to ON to build examples" ON)
option(CXXOPTS_BUILD_TESTS "Set to ON to build tests" ON)

If we set those to OFF, or just the example this would fix it.

ps: I don't think I'm alone in using cmake that way. I use it like that.

include(FetchContent)
FetchContent_Declare(cxxopts
    GIT_REPOSITORY "https://github.com/jarro2783/cxxopts"
    GIT_TAG "v2.1.2")

FetchContent_MakeAvailable(cxxopts)

And finally

target_link_libraries(${EXAMPLE_PROJECT_NAME} ${PROJECT_LIBRARIES} cxxopts ${PROJECT_NAME})
