### ISSUE TITLE
vector<string> for positional arguments with spaces not working

### ISSUE THREAD

**Issue by vinceplusplus** [jarro2783/cxxopts#27]
With the command line example as an example,
$ ./example "in put" "out put" "spaces not working"
will error out: "error parsing options: Argument ‘spaces not working’ failed to parse"
Without "spaces not working", the example program will parse without a problem

**Comment by jarro2783** [comment]
That's not so good. I'm looking at it.

**Comment by jarro2783** [comment]
Fixed in abab8ce.

**Comment by vinceplusplus** [comment]
Thanks, superb work
