### ISSUE TITLE
BUILD file causes annoying cmake issue

### ISSUE THREAD

**Issue by jpr89** [jarro2783/cxxopts#275]
By default when I create the build project for CMake I name my build directory 'build'.

This causes problems on windows due to case sensitivity. And it takes me a while to figure it out.

Perhaps consider renaming the BUILD file?

**Comment by jarro2783** [comment]
That's a bazel file. I think it has to be named exactly like that otherwise it doesn't work. Can you just build outside the source tree?

**Comment by jpr89** [comment]
"That's a bazel file. I think it has to be named exactly like that otherwise it doesn't work. Can you just build outside the source tree?"

Technically I could just change the build directory name. However, I'd like to point out that google test avoids this issue by naming their bazel file 'BUILD.bazel' (https://github.com/google/googletest)

**Comment by jarro2783** [comment]
I didn't realise that. I'll rename it.
