### ISSUE TITLE
Make the wiki read only

### ISSUE THREAD

**Issue by elliottt** [jarro2783/cxxopts#282]
The wiki was defaced about three months ago: https://github.com/jarro2783/cxxopts/wiki/Home/766fd8e70293d22ae2d1aa067367ad996a30ec31, so it might be worth making it read only.

**Comment by jarro2783** [comment]
Thanks for letting me know, I didn't even notice. I will fix it up.

**Comment by elliottt** [comment]
I reverted the change when I noticed it 👍

**Comment by jarro2783** [comment]
Yep I just saw, thanks. Any ideas how to make a wiki read only?

**Comment by jarro2783** [comment]
Never mind, I found the button. It was a bit hidden. Thanks for you help.
