### ISSUE TITLE
-Werror=null-dereference and GCC selection (potential issue)

### ISSUE THREAD

**Issue by blob42** [jarro2783/cxxopts#288]
Hi,

there might be an issue with the way the '-Werror=null-dereference' flag is put on the ignored diagnostics for GCC. The if statement 
<pre>
#if __GNUC__ <= 10 && __GNUC_MINOR__ <= 1
</pre>

does not perform a real if gcc <=10.1 check. E. g. when gcc 7.4.0 is used then the if statement will be false:
<pre>
#if 7 <= 10 && 4 <= 1
</pre>

Is this intentional? We came across this issue, because we are using gcc 9.3.0, 7.5.0, 7.4.0 and 8.1. And only for the latter one we get a complaint by the compiler, that
<pre>
error: '-Werror=null-dereference' is not an option that controls warnings [-Werror=pragmas]
</pre>

 Thanks in advance for your help. 

if you need more information please let me know

**Comment by jarro2783** [comment]
Yes that does appear to be wrong. I'll see if I can fix that.
