### ISSUE TITLE
Confusing thorwing message for non-presented mendatory option

### ISSUE THREAD

**Issue by EwingKang** [jarro2783/cxxopts#289]
Following code throws a confusing exception if executed WITHOUT any arguments.

``` bash
terminate called after throwing an instance of 'cxxopts::option_has_no_value_exception'
  what():  Option ‘’ has no value
Aborted
```

```c++
cxxopts::Options opt("Option test", "hahaha");

opt.add_options()
("h,help", "Help")
("sss", "some string", cxxopts::value<std::string>()) 
;
auto result = opt.parse(argc, argv);

if(result.count("help"))
{
    std::cout << opt.help() << std::endl;
    return false;
}
std::string aaa = result[std::string("sss")].as<std::string>();
```
I would think that the result should not be `has_no_value` but rather `option not exist` or something alike?

**Comment by jarro2783** [comment]
Which version are you using? I think this might have been fixed on master.

**Comment by EwingKang** [comment]
@jarro2783  Just tested with the latest master, it throws
 `what():  Option ‘sss’ has no value`
 correctly, thanks!
