### ISSUE TITLE
Create a release tag

### ISSUE THREAD

**Issue by mariobadr** [jarro2783/cxxopts#31]
Hi,

Thanks for the great library. Any chance you can create a release for the library? Something like v1.0? See https://git-scm.com/book/en/v2/Git-Basics-Tagging or take a look at https://github.com/nlohmann/json/releases for an example of a library that does this.

**Comment by jarro2783** [comment]
That sounds like a good idea. The library seems pretty stable now, I think it's ready for v1.0.0.
