### ISSUE TITLE
Where are tagged release versions?

### ISSUE THREAD

**Issue by pauljurczak** [jarro2783/cxxopts#315]
> Note that master is generally a work in progress, and you probably want to use a tagged release version.

Going to https://github.com/jarro2783/cxxopts/releases shows `There aren’t any releases here` message.

**Comment by jarro2783** [comment]
They're in the "tags" tab of that page.

**Comment by pauljurczak** [comment]
I see it. Thank you.

**Comment by eyalroz** [comment]
I'd suggest creating proper release pages, with some description of the changes since the previous release.

**Comment by jarro2783** [comment]
I think someone commented about that in another issue. I will make some releases in the next couple of days.
