### ISSUE TITLE
Parsing of command line arguments fails when using VSCode to debug

### ISSUE THREAD

**Issue by aosterthun** [jarro2783/cxxopts#316]
Hi,

I am using cxxopts for a while now, and never really had any problems with the library until today.
I code in VSCode and use the CMake Tools extension to manage my builds. VSCode provides at least two ways to debug. Either through the integrated debugger that can be configured using a launch.json or the debug tool provided through the CMake Tools extension. The latter can be configured directly through the setting.json file. 

However when I try to run the debugger I get a `cxxopts::option_syntax_exception` with the message: `what():  Argument ‘-p 1478’ starts with a - but has incorrect syntax`. When I run the executable without the debugger everything works fine and the command line arguments provided in the configuration files are used. 

I am also able to run the debugger manually. So when I start `gdb main` and then use `start -p 1478` to start the executable everything is fine.  

It seems like there is some problem passing the arguments along to the debugger. But I wasn't really able to obtain more info about this. 

Maybe someone in here has experienced the same thing and found a solution to this problem. I would appreciate any tips on how to solve this.

**Comment by jarro2783** [comment]
It sounds like the debugger is getting "-p 1478" as a single string, but it needs "-p" "1478" as two separate arguments.
