### ISSUE TITLE
Multicharacter short parameters

### ISSUE THREAD

**Issue by dady8889** [jarro2783/cxxopts#319]
Hello,
is there a way to specify parameter with multiple characters, also without having long name?

Common usage:

- setting levels of the parameter. (-v, -vv, -vvv, -vvvv => making output more verbose)
- having logically sorted options (-p1, -p2, -p3 => user knows those parameters fall into one category)

How I would expect it to work:
("v,", "Verbose level 1")
("vv,", "Verbose level 2")
("vvv,", "Verbose level 3")
("p1,", "Param 1")
("p2,", "Param 2")
("p3,", "Param 3")

In this format, the long name becomes optional instead.

**Comment by jarro2783** [comment]
That sort of syntax is not supported.

**Comment by jarro2783** [comment]
Although, for your two examples, you can have options that take multiple arguments, or can appear multiple times. So you can count how many times `-v` appears, and `-p` could be a vector of integers.

**Comment by dady8889** [comment]
Thank you for the suggestions, I will look into that.
However, one more thing I would like to do is something like 

-fa 100 -fb 200 -fc 300

This is basically what I mean with multicharacter short.
Would this be hard to implement? Could you maybe give some directions where to look to change it?

Thanks.

**Comment by jarro2783** [comment]
I don't really want to support that syntax since it's not standard compared to GNU options and many other Linux conventions. This can easily be done with `--`.
