### ISSUE TITLE
parse_positional & allow_unrecognised_options

### ISSUE THREAD

**Issue by actondev** [jarro2783/cxxopts#320]
Hi,

I stumbled upon a case where positional doesn't play well with unrecognized options

consider
``` c++
cxx_options.add_options() //
      ("file", "",
       ::cxxopts::value<std::string>())                                       //
      ("log-level", "eg debug info", //
       ::cxxopts::value<std::string>())                                       

  cxx_options.parse_positional({"file"});
  cxx_options.allow_unrecognised_options();

```

and then

``` sh
program --file foo.txt # ok
program --file foo.txt --log-level debug # ok
program --some-other-option bar --log-level debug # file gets the value of bar
```

I think that the positional arguments, when allowing unrecognized options, should be parsed up to the point of no unrecognized option has been passed.

**Comment by jarro2783** [comment]
That's a tricky case because it's not clear that `some-other-option` should actually take an argument.

**Comment by jarro2783** [comment]
I think the only way to handle this correctly is for those options to be passed as `--some-other-option=bar`.
