### ISSUE TITLE
Make the diagnostic pushes and pops not have to ifdef-GCC everywhere

### ISSUE THREAD

**Issue by eyalroz** [jarro2783/cxxopts#339]
Instead of sequences of lines like this:
```
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
```
we could just have:
```
DISABLE_WARNING_POP
```
_and_ make that support multiple compilers if/when you want to. See how this is done, for example, in [this file](https://github.com/eyalroz/printf/blob/master/test/test_suite.cpp) of mine. The relevant code starts at line 97.

**Comment by jarro2783** [comment]
That looks much cleaner, I'll do something like that.

**Comment by eyalroz** [comment]
> Recommend defining CXXOPTS_DIAGNOSTIC_PUSH & POP as empty , when __GNUC__ is not defined .

Actually, one should make the relevant MSVC definitions:
```
#if defined(_MSC_VER)
    #define DISABLE_WARNING_PUSH           __pragma(warning( push ))
    #define DISABLE_WARNING_POP            __pragma(warning( pop ))
    #define DISABLE_WARNING(warningNumber) __pragma(warning( disable : warningNumber ))
#endif
```
Note that for specific warnings, one then has to make definitions translating a warning macro to a number of name which is different for GCC and MSVC. But for disabling all warnings just the first two lines within the ifdef here are enough.

**Comment by jarro2783** [comment]
Oops. There aren't any pragmas for MSVC, so I might as well just define it to nothing for now.
