### ISSUE TITLE
Inconsistent indentation in namespaces

### ISSUE THREAD

**Issue by eyalroz** [jarro2783/cxxopts#340]
Many definitions/declarations in namespace cxxopts are indented by 2 spaces. But - the implementation functions (inline's after the class definitions) - are not indented. Suggest not indenting within namespaces, consistently.

**Comment by jarro2783** [comment]
I was probably going for declarations being indented and the actual code not indented, but as you noticed this just leads to inconsistencies.

**Comment by eyalroz** [comment]
As I'm working on #240 , I'm finding the namespace indentation super-annoying. Would really like it to go away. Would you take a PR for that?
