### ISSUE TITLE
option_required_exception and option_not_present_exception sound like the same thing

### ISSUE THREAD

**Issue by eyalroz** [jarro2783/cxxopts#346]
Why is there an `option_required_exception` but also an `option_not_present_exception`? It sounds like they're about the same situation.

Looking at the code, `option_not_present` is when you're looking up an option in a ParseResult instance. Well, in that case, I'd rename: `required_option_missing_exception` and `requested_option_missing` / `requested_option_present`.

**Comment by jarro2783** [comment]
`option_required_exception` doesn't appear to be constructed, so feel free to delete that.
`option_not_present` is for looking up an option that doesn't have a value.

**Comment by eyalroz** [comment]
@jarro2783 : Removed the unused one.
