### ISSUE TITLE
An attribute list can not appear here

### ISSUE THREAD

**Issue by maidamai0** [jarro2783/cxxopts#354]
clang complains about the `An attribute list can not appear here`:
https://github.com/jarro2783/cxxopts/blob/e976f964c3ee6a4f6faa836ecb38f3ff8b043114/include/cxxopts.hpp#L1252

move the `CXXOPTS_NODISCARD` before `inline` can make clang quiet

**Comment by jarro2783** [comment]
Duplicate of #353
