### ISSUE TITLE
Missing std::cerr when using CXXOPTS_NO_EXCEPTIONS

### ISSUE THREAD

**Issue by operatios** [jarro2783/cxxopts#356]
iostream was recently removed as unused in: https://github.com/jarro2783/cxxopts/commit/6c8a41a229e133e6f9a0f5c9b490870afc1a31f1. But this leads to the error below if CXXOPTS_NO_EXCEPTIONS is defined:
```
cxxopts.hpp:556:8: error: no member named 'cerr' in namespace 'std'
  std::cerr << exception.what() << std::endl;
  ~~~~~^
1 error generated.
```
Including it back again obviously solves the issue, so the commit should probably be reverted?

**Comment by jarro2783** [comment]
Oops, fixed.
