### ISSUE TITLE
Building on MacOS fails

### ISSUE THREAD

**Issue by hillmich** [jarro2783/cxxopts#369]
As of now, MacOS still fails (PR #368 did not fix it, sorry I messed that up).

I forked the repo and made quite a lot of changes trying to make `std::isblank` work on [hillmich/cxxopts](https://github.com/hillmich/cxxopts). The main change is to replace `std::isblank` by explicitly checking for space and tab as the [standard](https://en.cppreference.com/w/cpp/string/byte/isblank#See_also) dictates for the C locale. This fork also includes

- CI on MacOS and Windows
- Assume header `regexp` is always there since cxxopts requires c++11 or higher (and eliminate a large chunk of code)
- Remove some unused headers
- Get around requiring `cstring`
- Add `std::` to instances of `size_t`

@jarro2783 are you interested in these changes and would you accept them as PR?

**Comment by jarro2783** [comment]
sounds good, make a PR and I'll take a look.

**Comment by VictorEijkhout** [comment]
Progress on this? I'm in need of this fix.

**Comment by jarro2783** [comment]
Sorry I got distracted by something else, I'll follow up on that PR.
