### ISSUE TITLE
Can't specify only a short option

### ISSUE THREAD

**Issue by RedDwarf69** [jarro2783/cxxopts#37]
If in the example code you change "a,apple" for "a" then "-a" is not accepted as a valid option any more.

**Comment by jarro2783** [comment]
This was intentional. I intended that you must set a long option, and an optional short option. In fact long options must be two characters or more, so I'm surprised that you didn't get an exception trying to add an option that is just "a".

**Comment by RedDwarf69** [comment]
OK, makes sense.

I was just testing the library and considered it a bug because I had just read "Options can be declared with a short and/or long option" in the README.md file. "short and/or long option" seems confusing to me if a short option only is not supposed to be valid (disclaimer: I'm not a native English speaker). Maybe the wording in the docs could be changed, but otherwise this issue can probably be closed.

**Comment by jarro2783** [comment]
Yes I will improve the wording.
