### ISSUE TITLE
Could cxxopts process arguments without any option?

### ISSUE THREAD

**Issue by Lw-Cui** [jarro2783/cxxopts#38]
Like gcc we could write like `gcc -O3 a.cpp -o a.out`. Could cxxopts process arguments without any option?

**Comment by jarro2783** [comment]
If I understand correctly, look at `src/example.cpp`, the `b,bob` option does not take any arguments. You can then query it with `count("b")`.

Does that answer your question?

**Comment by Lw-Cui** [comment]
Thanks for reply.
Maybe I confused the meaning of 'option' and 'argument'.
I'd like to performance like gcc: `gcc a.cpp -o a.out`, which could handle `a.cpp` directly without any option specified.
So does cxxopts have this feature?

**Comment by jarro2783** [comment]
Ok I understand now. Yes that can be done with positional parameters. See https://github.com/jarro2783/cxxopts/blob/master/src/example.cpp#L62 

Parameters are parsed into options in the order specified in `parse_positional`, until a container option is reached, and then it just fills up that option.

**Comment by Lw-Cui** [comment]
Thanks a lot!
Now I really understand the point of `postitonal arguments`.
Have a great day:)

**Comment by feliwir** [comment]
Hello, i wanted to ask if this is also possible without any specific position. In gcc it can be without any specifc positions like this for example: "gcc -o out.a a.cpp b.cpp c.cpp" which is the equivalent to "gcc a.cpp b.cpp c.cpp -o out.a". To me this doesn't seem possible currently. Thanks

**Comment by Lw-Cui** [comment]
Hi. If you write
```
options.parse_positional({"src"});
auto& v = options["src"].as<std::vector<std::string>>();
for (const auto &str: v) cout << str << endl;
```
Then the output will be
```
a.cpp
b.cpp
c.cpp
```
Hope that answers your question

**Comment by feliwir** [comment]
Not sure which compiler you are using, but that doesn't work with MSVC 2017 (Error: ambigious call to overloaded function)
