### ISSUE TITLE
Report a typo in README.md doc(in master branch)

### ISSUE THREAD

**Issue by pagesus** [jarro2783/cxxopts#410]
In README.md doc, 
(1) I find that in section **[Version 3 breaking changes](https://github.com/jarro2783/cxxopts#version-3-breaking-changes)** said: **the ParseResult object no longer depends on the parser.**
(2) But I also find in section **[Basics](https://github.com/jarro2783/cxxopts#basics)** said:  **Note that the result of options.parse should only be used as long as the options object that created it is in scope.**

I review the code, and find the ParseResult is independent of parser, so the description in (2) is a typo?

**Comment by jarro2783** [comment]
Yes you are right. I missed that later section when I first made that change. Thanks.
