### ISSUE TITLE
What is the use of constructor parameters in options("MyProgram", "One line description of MyProgram")?

### ISSUE THREAD

**Issue by pauljurczak** [jarro2783/cxxopts#415]
What is the use of these two strings?
```
cxxopts::Options options("MyProgram", "One line description of MyProgram");
```

**Comment by jarro2783** [comment]
They are both used in the help string produced by `--help`.

**Comment by pauljurczak** [comment]
It seems that `help` option has to be defined for this to work. Otherwise, I'm getting:
```
terminate called after throwing an instance of 'cxxopts::exceptions::no_such_option'
  what():  Option 'help' does not exist
```

**Comment by jarro2783** [comment]
Yes there is no default way to print the help, so that you can make it
behave as you want for your program. You can add a help option to print it
if you want.
