### ISSUE TITLE
Provide "positional parameters" text 

### ISSUE THREAD

**Issue by androticus** [jarro2783/cxxopts#43]
The wording "positional parameters" is quite technical, and I would prefer to specify what this should be, when I set up the options. Currently, I am doing this manually using a string replace of the help text before presenting it to my user. For example, in my application, I actually present this text:
[SCHEMA ...]

I was confused about this, since the "positional" option in the example.cpp did provide text for this, but I looked at the code, and it seems to just be hardwired to "positional parameters".

Thanks for considering this!

**Comment by jarro2783** [comment]
That's not a problem, I'll make it a parameter.

The reason that the help can't use the help string from some arbitrary positional parameter is because there might be more than one parameter used to handle positional parameters. It isn't obvious which one should be used if there are more than one.

**Comment by jarro2783** [comment]
I have added this feature. It is set by calling `positional_help` on an `Options` object before generating the help text.
