### ISSUE TITLE
What cmake targets are defined?

### ISSUE THREAD

**Issue by VictorEijkhout** [jarro2783/cxxopts#432]
I'm trying to include cxxopts in a project. My random guess:
```
include( FetchContent )
FetchContent_Declare(
    cxxopts GIT_REPOSITORY https://github.com/jarro2783/cxxopts.git )
FetchContent_MakeAvailable( cxxopts )
target_include_directories( ${PROJECT_NAME} INTERFACE cxxopts::cxxopts )
target_link_libraries( ${PROJECT_NAME} INTERFACE cxxopts::cxxopts )
```
leads to unresolved symbols.
Could you document what the `.cmake` files provide?

**Comment by jarro2783** [comment]
What are the unresolved symbols? That looks like it's the right target, although I'm not familiar with including a project in that way. There is only one header, so I'm not sure what could actually be missing.

**Comment by VictorEijkhout** [comment]
I upgraded to 3.2.0 and now that target works. Thanks.
