### ISSUE TITLE
Required arguments

### ISSUE THREAD

**Issue by netw0rkf10w** [jarro2783/cxxopts#44]
Hi, 
Thanks for the software.
It would be great if there is an option to set some arguments as 'required', like in Boost::program_options:

```
std::string input;
boost::program_options::options_description options("Some arguments");
options.add_options()
        ("input", boost::program_options::value<std::string>(&input)->required(), "Path to input file")
;
```
Regards.

**Comment by jarro2783** [comment]
I'm reluctant to do this, and something similar was raised in #25. The reason being that I don't think the parser should have any logic in it. The problem is that in general, you can't just say that an argument is required or not. There are some specific cases where it works, but a lot of the time, arguments are required based on the presence of other arguments. I would rather leave that logic up to the program.

**Comment by crusader-mike** [comment]
I agree with OP -- simple method will certainly simplify my life (as in I don't need to write it myself). Something very trivial, like:
```
class Options {
...
template<class T>
T required_option_(string const& opt)
{
    if (!count(opt))
        throw ...(u8"Option ‘%s’ is required", opt.c_str());
    return (*this)[opt].as<T>();
}
...
};
```

Also, you may want to clean up this code a bit -- I skimmed over it and noticed few strange pieces (like calling _std::move_ on _string const&_). Don't take it personally -- it is a neat little library and it seem to get it's task done.

**Comment by jarro2783** [comment]
I'll see if I can add something simple for required options. It seems to be the most requested feature, and something simple should be ok. As long as it is understood that anything more complicated belongs in the main program.

Thanks for pointing out the strange things in it. It has been around for a while and acquired some cruft.

**Comment by patrikhuber** [comment]
Hi,

I have been searching for this for quite a while. I don't think this is documented anywhere. Shall we add this to the wiki? It's meant to be used as follows, correct?

`cxxopts::check_required(options, { "option1", "option2" });`

**Comment by patrikhuber** [comment]
It looks like `cxxopts::check_required` is not present anymore in the current cxxopts version, it must have been removed again.

**Comment by eyalroz** [comment]
@jarro2783 : Can you clarify regarding whether marking options as required is currently supported? Looking at the latest release, it doesn't seem like it is.

**Comment by jarro2783** [comment]
No this isn't supported.

**Comment by eyalroz** [comment]
@jarro2783 : Ok, so... can you reopen this bug? Shall a new one be filed? You wrote that:

> I'll see if I can add something simple for required options. It seems to be the most requested feature, and something simple should be ok.

and while it's true that was 9 years ago, it still seems relevant.

**Comment by patrikhuber** [comment]
9 years later I'm also still in the market for this 😅

**Comment by jarro2783** [comment]
I think I never wanted to do a simple hacky version of this, because it opens up putting much more logic about constraining option values. It also adds error reporting that users might prefer to do themselves. I would prefer something standalone that checks option constraints, but I never got around to it.

**Comment by eyalroz** [comment]
Well, it's your call of course, but - simple is not hacky... Marking an argument as required is not the same as constraining values, and I doubt this would that up more than it is open now. Of course, users can always add their own checks, but this one seems like a straighforward and common thing to require, to the extent that the command-line argument parser can be the one to issue the error. My two cents anyway.
