### ISSUE TITLE
Positional arguments (with corresponding option invisible)

### ISSUE THREAD

**Issue by crusader-mike** [jarro2783/cxxopts#45]
I need to do precisely what OP in #15 described. Is there any way to achieve it now?

**Comment by jarro2783** [comment]
There is no magical solution for positional options to have their help hidden. What you can do though is to put them in another group. Then when you print the main group options out, they will not be shown.

Does that answer your question?

**Comment by crusader-mike** [comment]
So, the only way to declare positional arguments is to "tie" them into an "option", which always has visible help (unless in another group). Is this correct?

If yes -- this will work for workaround.

**Comment by jarro2783** [comment]
Yes that's correct. `--` works too.
