### ISSUE TITLE
implicit value is used when arg is 'empty string'

### ISSUE THREAD

**Issue by crusader-mike** [jarro2783/cxxopts#46]
I have an option with implicit argument (let's say `-w [<arg>(=ABC)]`). When I invoke my app with arg = 'empty string' (i.e. `<mybinary> -w ""`) -- option takes value of 'ABC'.

I am pretty sure shell passes such cmdline params as empty strings into _main()_. Looks like a bug.

**Comment by jarro2783** [comment]
Sounds like a bug. I'll have a look at it.

**Comment by jarro2783** [comment]
I found the offending piece of code. This might need a bit of refactoring to fix, so no guarantees on how long it will take me.

**Comment by crusader-mike** [comment]
No probs, it is minor. I suspect logic somewhere inside used implicit value if arg is empty (as opposed to 'arg is not specified'). Default value handling might have same problem (I didn't check).
