### ISSUE TITLE
Allow using only short arguments

### ISSUE THREAD

**Issue by marmistrz** [jarro2783/cxxopts#47]
It would be great if it were possible to use only short arguments in some cases:
```
opts.add_options()("p", "The parameter p in the algorithm", cxxopts::value<bool>());
```
Example (alternative) syntax:
```
// empty string shows there's no long option
opts.add_options()("", "p", "The parameter p in the algorithm", cxxopts::value<bool>());
```

**Comment by jarro2783** [comment]
In my opinion every short option should always have a long option so that readable options can be written down in code. But it's not my business what you do with your programs, so I will allow short options.
