### ISSUE TITLE
Exclusive groups

### ISSUE THREAD

**Issue by marmistrz** [jarro2783/cxxopts#48]
Sometimes we only want to allow only one of a few options at one time.

```
    opts.add_options()
            ("file", "Read data from file", cxxopts::value<std::string>())
            ("generate", "Generate a random network")
            ("anothergenerate", "Generate a random network with a different algorithm");
```

It would be really useful to mark a group as exclusive, so that `cxxopts` would raise an error when two of the opts are used.

**Comment by jarro2783** [comment]
This is the sort of logic that I don't want to add, as also discussed in #44 and #15. I think this clearly falls in the realm of the program. On the other hand, in your example, you could have an option `--algorithm`, which obviously only allows one thing to be set.

**Comment by marmistrz** [comment]
I don't think it's a really great logic here - just validation constraints.
