### ISSUE TITLE
no cxxoptsConfig.cmake after installing with cmake ../ && make install

### ISSUE THREAD

**Issue by Glavnokoman** [jarro2783/cxxopts#52]

**Comment by jarro2783** [comment]
I don't know what this file is supposed to be. Why would I expect it to exist?

**Comment by Glavnokoman** [comment]
This is to make it easy to use cxxopts with cmake projects. For those who
do not want to include it in the project sources but to access through
findPackage.

**Comment by jarro2783** [comment]
#53 has given me some more context. I will get to that pull request and that should sort out the problem.

**Comment by jarro2783** [comment]
Closed by #53
