### ISSUE TITLE
Implicit / Default bool values

### ISSUE THREAD

**Issue by edkimmel** [jarro2783/cxxopts#54]
Right now, bool parsing is left as a TODO that just always says true.

Given:
`
("r,recursive", "Do the thing recursively", cxxopts::value<bool>()->default_value("")->implicit_value("true"))
`
I expect the following:

- If the option is missing entirely, it is false.
- If the option given as -r or --recursive without a value, it's interpreted as true.
- If a value is given, it's parsed from common "truthy" strings.

**Comment by jarro2783** [comment]
I'll get to this soon. Thanks for the bump. I'm working on improving the numeric parsing, so I'll do this one next.
