### ISSUE TITLE
Is there any way to disallow arguments to be used like -abc?

### ISSUE THREAD

**Issue by danechitoaie** [jarro2783/cxxopts#56]
I have defined the following options.

```
        options.add_options()
            ("c,clean"  , "Clean folder")
            ("p,project", "Path to project file", cxxopts::value<std::string>())
            ("h,help"   , "Print help");
```

And it can be used with `program -c` or `program --clean` which is perfect.

Is there anyway to disable it from working like `program -chp` ?
This basically triggers all three options, like I would've used `program -c -h -p something`.

**Comment by jarro2783** [comment]
This is by design, it's supposed to do that, similar to GNU Tar. There is currently no way to disable that behaviour.

**Comment by danechitoaie** [comment]
Ok, thanks.
