### ISSUE TITLE
Adding options with space causes program crash

### ISSUE THREAD

**Issue by sikinmettugi** [jarro2783/cxxopts#57]
Hello, I am about to ask a question, by raising this issue.

## Summary
- add_options() crashes when cla option definition string has a space in it, and want to know if this is intended.

## Environment
- VS2015 on Windows 7 x64
- Debug(x86) is current project configuration

## How to Reproduce This
```C++
cxxopts::Options options(argv[0], "Program for cxxopts");

options.add_options()
    ("d, debug", "Enables debug")
; // Note the space after "d,"
```

This causes crash at `cxxopts.hpp:1018`: `cxxopts::invalid_option_format_error`
```C++
const auto& short_match = result[2];
```

## Why Do I Raise This Issue
- I am new to C++ CLA library, and not sure if no whitespace between short/long option is allowed.
   - Is this a known convention when writing a CLA option?
- Since I am also new to C++ regex handling, thus not sure if I can handle this issue such fast.

**Comment by jarro2783** [comment]
It shouldn't crash. It seems reasonable to allow a space there. It should be no problem to add that in.

**Comment by sikinmettugi** [comment]
Thx for the response. I added my working environment and which exception were raised.
So, as I understand, this crash is unintended, right?

**Comment by jarro2783** [comment]
It was intended when I wrote it. The options should not have a space between them. But I can't see any reason why they shouldn't, and it's easy to change.
