### ISSUE TITLE
Parsing types other than standard ones

### ISSUE THREAD

**Issue by dagenest** [jarro2783/cxxopts#60]
README.md says "_Any type can be given as long as it can be parsed, with operator>>_." but it does not work for types such as enum classes. In fact, i don't see any call to operator>> in the source.
Defining void parse_value(const std::string& text, _MYTYPE_ & value) works perfectly, and throwing a cxxopts::argument_incorrect_type in parse_value for a wrong value also works perfectly.
Is defining parse_value the right way to do it (so i suppose the README needs an update, because it is a interesting feature), or is it just an undocumented feature that could be removed in future releases?

**Comment by jarro2783** [comment]
Ah right, I think I actually broke that recently with the improved integer parsing.

From 5e9f8225982e9711b548c886fe6b477cdefd0fd4:

```diff
     template <typename T>
     void
-    parse_value(const std::string& text, T& value)
+    integer_parser(const std::string& text, T& value)
     {
-      std::istringstream is(text);
-      if (!(is >> value))
```

So I actually did previously intend to use `operator>>` to parse values. I will put that back in.

Of course you can override it by overloading `parse_value`, and that would be the correct way to work around it for now.
