### ISSUE TITLE
Multiple definitions 

### ISSUE THREAD

**Issue by gouarin** [jarro2783/cxxopts#61]
I would like to use cxxopts in several source files but it seems that it is not possible. I have compilation errors mentioning that there exists multiple definitions.

To have an example, I just take the one given in the source code and I have added `sum.hpp` and `sum.cpp` with the following content

```
#ifndef SUM_HPP
#define SUM_HPP

#include "cxxopts.hpp"
double sum(double a, double b);
#endif  
```

```
#include "cxxopts.hpp"
#include "sum.hpp"

double sum(double a, double b)
{
    return a + b;
}
```

And then I have added 

```
#include "sum.hpp"
```

and I have added the source file `sum.cpp` in the `CMakeLists.txt`. When you compile this example, you will have multiple definitions error.

**Comment by jarro2783** [comment]
I'll take a look at this.

**Comment by gouarin** [comment]
Thanks.
