### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by gouarin** [jarro2783/cxxopts#65]
@jarro2783 we use your project to manage the options in a Jupyter cell with https://github.com/QuantStack/xeus-cling.

We would like to package your application in order to install cxxopts with conda and to manage the dependencies of our xeus-cling project. But to be able to do that, we need a new release with the fix https://github.com/jarro2783/cxxopts/issues/61. 

@SylvainCorlay will do the packaging for conda. 

Could you do a new release ?

**Comment by jarro2783** [comment]
Yeah sure, can't do it right now, but I'll get to that today.

**Comment by jarro2783** [comment]
I was trying to fix the OSX build on travis, but I couldn't, so I've disabled it for now and made a tag.

**Comment by SylvainCorlay** [comment]
@jarro2783 it does not seem that you have pushed your tag.

**Comment by jarro2783** [comment]
Ah, it certainly doesn't. I did `git push --all`, I thought that included tags. I will push that shortly.

**Comment by SylvainCorlay** [comment]
FYI cxxopts is on `conda-forge`!
