### ISSUE TITLE
Reparse not possible without a reset method or alike

### ISSUE THREAD

**Issue by Larswad** [jarro2783/cxxopts#67]
I discovered that after one parse() call, the state of the parsed options is kept if doing a new parse (with different argc/argv). Parse would need to reset the state before starting, either by implicit or that the user has to call to a reset method or such.

**Comment by jarro2783** [comment]
I never thought of that use case, it was always intended as a one off parse.

Is the only reason so that you can save a bit of time by not building the options again?

**Comment by Larswad** [comment]
Thanks for the answer! Well, beside the typical one-off parse main() argc/argv scenario, I saw a very nice use for cxxopts in a command parser for my debug console, where each implemented command has its own member instance of Options (and each command populates the options and positionals in their constructor). They implement a pure run method in which they first parse and then do their stuff. But multiple runs in this case doesn't work, in fact its the only thing that prevents it. In all other aspects it works nicely as a fullblown command parser (I do construct the argc/argv lists on my own originating from a std::string, to a std::vector<std::string> and then into argc/argv.

It tried implementing this in Options:
```
	// reset state of values.
	inline void reset()
	{
		for(auto option : m_options)
			option.second->reset();
	}
```
and in OptionDetails:
```
	void reset()
	{
		m_count = 0;
		m_value.reset();
	}

```
(Calling reset() before parse, or inside parse) But hmm, that wasn't enough. Probably I've misunderstood something.

**Comment by Larswad** [comment]
Think it should be like this (forgot it had to be a reference, of course):
```
	// reset state of values.
	inline void reset()
	{
		for(auto& option : m_options)
			option.second->reset();
	}
```
and in OptionDetails:
```
	void reset()
	{
		m_count = 0;
	}

```

**Comment by Larswad** [comment]
No, I don't succeed in the reset() method. Damn this was hard to penetrate. Should have been the easiest thing...but. The const templated stuff goes deep. Would be grateful for any hint.

**Comment by Larswad** [comment]
Ok, think I finally solved it. The positionals iterator must be reset as well. So the reset method looks like:
```
	// reset state of values.
	inline void reset()
	{
		for(auto& option : m_options)
			option.second->reset();
		m_nextPositional = m_positional.begin();
	}

```

**Comment by jarro2783** [comment]
That will probably work, and I can add that if it is really needed.

What I was trying to get at earlier is that you could avoid needing that by having a parse function that builds the `Options` object and returns the results.

Is there any particular reason that you can't do something like this:
```
R
parse(const std::vector<std::string>& args)
{
  cxxopts::Options options;
  // add arguments

   options.parse(args);

  // inspect options and build a result object

  return result;   
}
```

**Comment by Larswad** [comment]
Thanks. Well, I guess I could provide such a construction method in my command class, even though I'm trying to keep down the amount of methods since I expect the amount of classes to grow (right now the constructor is responsible for that. From a performance/heap-thrashing point of view though I feel that the parser should accept multiple calls without reconstructing it. But that design choice is of course your call. Anyways, thanks for helping out. Maybe the call to a reset could be left to the user, I mean, that way the user could in principle do multiple calls with complementary arguments, keeping the current parsed arguments? Just an idea.

**Comment by Larswad** [comment]
BTW, just a side note. The positional arguments in the help text looks funky to me. I'll send you an example when I get back to work on Monday.

**Comment by jarro2783** [comment]
It's more that I feel like having a reset is a bit of a hack. But then it probably shouldn't let you call parse multiple times either. Probably a better design would be to return the result, with the Parser class being immutable. But that would need a bit of a redesign.

How often are you calling the parser? Unless it's in a performance critical part I wouldn't haven't thought that it was that bad to just construct it every time.

**Comment by jarro2783** [comment]
This is now done with the rewrite.
