### ISSUE TITLE
options.help({}) doesn't show positional arguments sometimes

### ISSUE THREAD

**Issue by meijin007** [jarro2783/cxxopts#72]
Code sample:
```
int main(int argc, char *argv[]) {
    try {
        cxxopts::Options options(argv[0], "Sample");
        options.positional_help("<Extra args>");
        
        options.add_options()
        ("s,set", "Set whatever.", cxxopts::value<std::vector<std::string>>())
        ("h,help", "Print help and exit.")
        ;
       
        options.parse(argc, argv);
        options.parse_positional({"file", "remove-label", "set-label"});
       
        // help
        if (options.count("help")) {
        cout << options.help({""}) << std::endl;
        exit(0);
        }
    } catch (const cxxopts::OptionException& e) {
        cout << "error parsing options: " << e.what() << std::endl;
        exit(-1);
        }
    return 0;
}
```

Expected: Show the "set" option in the help.
Actual: Show only "help" option.

**Comment by jarro2783** [comment]
You've used `parse_positional` incorrectly, although that shouldn't affect the help options. I'll take a look at why help is doing the wrong thing.

For `parse_positional`, you need to call it before `parse`, and it needs to be a list of actual options, otherwise positional arguments will result in an a missing option error.

**Comment by jarro2783** [comment]
This is what I get
```
Sample
Usage:
  ./bad [OPTION...] <Extra args>

  -s, --set arg  Set whatever.
  -h, --help     Print help and exit.
```

**Comment by meijin007** [comment]
it's seems like it's a come-and-go thing. 
Can I give a private branch on my repo where it always happens?

**Comment by meijin007** [comment]
Sorry for the inconvenience.

can you try this code please:
```
int main(int argc, char *argv[]) {
  try {
    cxxopts::Options options(argv[0], "Sample app for Microsoft Information Protection SDK");
    options.positional_help("<Extra args>");

    options.add_options()
        ("s,set-label", "Set a label with <labelId> and with owner <owner>.", cxxopts::value<std::vector<std::string>>())
        ("h,help", "Print help and exit.")
        ;

    options.parse_positional({"file", "remove-label", "set-label"});
    options.parse(argc, argv);

    // help
    if (options.count("help")){
      cout << options.help({""}) << std::endl;
      exit(0);
    }
  } catch (const cxxopts::OptionException& e) {
    cout << "error parsing options: " << e.what() << std::endl;
    exit(-1);
  }

  return 0;
}
```

It's happen only with set-label as an argument. which is very weired.
Thanks,

**Comment by jarro2783** [comment]
That reproduces it, thanks.

**Comment by meijin007** [comment]
also happens if you call the arg "setlabel"

**Comment by jarro2783** [comment]
I just realised that this is expected. See: https://github.com/jarro2783/cxxopts/blob/0b7686949d01f6475cc13ba0693725aefb76fc0c/include/cxxopts.hpp#L1615

If it's a positional argument it isn't printed in the help, because the expectation is that it will be set by non-option arguments.

**Comment by meijin007** [comment]
is there any way to pass this or change my design that way it will show this option in the help?

**Comment by jarro2783** [comment]
See #25 as to why this was implemented.

Do you actually want a positional option that can take multiple arguments *and* shows up in the help?

**Comment by meijin007** [comment]
Yes... "set-label" get 1 mandatory argument and 2 optional

**Comment by jarro2783** [comment]
Ah right. So are you saying that you want users to write `--set-label foo`, but then write `bar baz` later which will be attached to the same option?

Can you use a second option to split them up?

The help for positional options isn't particularly good. I could probably look at improving that, and making it optional to turn the help back on.

**Comment by meijin007** [comment]
It will make no sense to do it this way. I would really appreciate if you can improve it.

**Comment by jarro2783** [comment]
Sure I'll make some improvements.

**Comment by meijin007** [comment]
It also seems that passing multiple args to positional isn't parsed at all. in this example, passing 
`-s "123" "Assaf" `
only the first argument get parsed into the vector<std::string>

**Comment by jarro2783** [comment]
In this case, the `123` is a parameter of `-s` if it takes parameters, otherwise both `123` and `Assaf` should both be parsed into whatever the positional arguments are declared as.

**Comment by meijin007** [comment]
so if `-s` is need to get multiple parameters, how should I define it?

**Comment by jarro2783** [comment]
The `-s` needs to be used each time. Similar to the `-l` flag of GCC.

**Comment by meijin007** [comment]
hi - any news regarding this?

**Comment by jarro2783** [comment]
Sorry not yet.

**Comment by TheMaverickProgrammer** [comment]
This bug is still present. I had to take out `parse_positional` because my flags were not showing up in the help message.

**Comment by SimLeek** [comment]
Use `show_positional_help()` if you need detailed info for the positional arguments.

Just got this working:
```
cxxopts::Options options("the_exe", "It does things");

options.add_options()
("h,help", "Print help info", cxxopts::value<bool>()->default_value("false"))
("s,sub", "subscriber address", cxxopts::value<std::string>())
("p,pub", "publisher address", cxxopts::value<std::string>())
;

options.positional_help("<sub> <pub>");

options.parse_positional({"sub", "pub"});

options.show_positional_help();
```

Which gives:
```
It does things
Usage:
  the_exe [OPTION...] <sub> <pub>

  -h, --help     Print help info
  -s, --sub arg  subscriber address
  -p, --pub arg  publisher address
```

**Comment by blex-max** [comment]
As in the example above, this doesn't remove the positional args from the option helptext. Is it not possible to have positional only arguments?
