### ISSUE TITLE
Is iterating over the options possible?

### ISSUE THREAD

**Issue by Malvineous** [jarro2783/cxxopts#74]
Is it possible to iterate over the non-positional options?

My program works by performing actions, in order, as they are specified on the command line.  So for example I might do something like this:

    ./example --add newfile.txt --delete existing.txt --rename newfile.txt=existing.txt

If those operations happen in a different order then the program won't work, so I need a way to find out what the first option and its parameter are (and action it), then look at the second option and its parameter, and so on.

`boost::program_options` offers a `std::vector` of the options, in the order given on the command line - is there an equivalent here, or some other way to achieve this functionality?

**Comment by jarro2783** [comment]
This is currently not possible. It's not something I ever thought of doing. It shouldn't be too hard to add though.

**Comment by Malvineous** [comment]
Sounds good!  Without wanting to be annoying, do you know what sort of a timeframe it might take to get implemented?  I'm quite keen to move away from `boost::program_options` :-)

**Comment by jarro2783** [comment]
I have a few improvements to make, with one that is probably backwards incompatible, so I'm thinking of doing a new major version release, which this would be included in. I don't have much time to work on this, so probably a few weeks.

**Comment by jarro2783** [comment]
I'm trying to work out the best interface for this. I can't find anywhere in the Boost docs that mentions this feature. Can you give me a link so that I can see how they do it?

**Comment by Malvineous** [comment]
Not sure where in the docs as they aren't the easiest to read, but this is my own code that uses this feature:

  https://github.com/Malvineous/libgamearchive/blob/master/examples/gamearch.cpp#L425

Essentially it looks like the object that is returned after parsing the command line has `begin()` and `end()` functions so it can be iterated over.

It'd be nice if it was compatible with C++11 loops, like this:

  https://github.com/Malvineous/libgamearchive/blob/master/examples/gamearch.cpp#L649

Note that each element in the list is an option (starting with `-` or `--`) and that option's parameters are kept with it.  So:

    example --first --second=beta --third gamma

Means in the loop, `item[0].string_key` is `first`, `item[1].string_key` is `second`, `item[1].value[0]` is `beta`, `item[2].value[0]` is `gamma`, etc.

I'm not saying this is the only way to do it, just explaining how Boost does it.  If you had a list of tokens instead (without combining options and their parameters into the same object) then that would work for me, as long as I could "eat" one or more tokens in the middle of the loop, depending on whether the option I'm processing has any parameters or not.

**Comment by jarro2783** [comment]
Does this work when you do `--first value --second foo --first bar`?

As in you get `--first` with value `bar` in the third iteration? My problem with that is at the moment container values are parsed transparently into their container, so it would know which argument it is up to but lose which actual value it just parsed.

I'm just thinking about whether to restructure this all or if it seems ok to fit it into the current design.

**Comment by Malvineous** [comment]
Yes, that is correct.

You can't use `.back()` or similar to get the last value parsed?  Sorry I'm not familiar with the architecture.
