### ISSUE TITLE
Major changes to the API

### ISSUE THREAD

**Issue by jarro2783** [jarro2783/cxxopts#76]
In order to facilitate several requested enhancements I will be making major backwards incompatible changes to the API, and releasing it as version 2.0.

This issue is here to track the progress of the changes.

The biggest change will be the way parsing is handled. Rather than making a stateful change to the parser object, parsing will be stateless, and will return the result of the parse. This will allow for reusing the parser, and should also make it easier to iterate through the match results.

**Comment by giumas** [comment]
How to manage when the parser fails throwing an exception? Before I was using something like this:

	try
	{
		options.parse(argc, argv);
	}
	catch(const cxxopts::OptionException& e)
	{
             [...]
	}
