### ISSUE TITLE
Problems when passing incorrect numbers

### ISSUE THREAD

**Issue by DevCodeOne** [jarro2783/cxxopts#78]
I write an application which I need to pass a debug level for logging. 
As I tested my application I tried to catch all exceptions so I could provide good error messages for the user. When I tried to enter a string instead of an integer no exception got thrown, instead it parsed it to a valid integer. Also for the parser 0x0 is not a valid integer.
Furthermore when entering a decimal number without 0x it is still possible to use A-F in the number.

Test program:
```c++
#include "cxxopts.hpp"

int main(int argc, char *argv[]) {
    cxxopts::Options options("test", "");
    options.add_options()("d,debug", "enable debugging", cxxopts::value<int>());
    try {
        options.parse(argc, argv);

        if (options.count("debug")) {
            std::cout << options["debug"].as<int>() << std::endl;
        }

    } catch (cxxopts::argument_incorrect_type e) {
        std::cout << "The provided argument is of a wrong type" << std::endl;
    } catch (...) {
    }
    return 0;
}
```
Example outputs:
1.)

```
./testprogram -d 0x0
The provided argument is of a wrong type
```
2.)

```
./testprogram -d Ae
114
```
3.)
```
./testprogram -d test
1400
```
Expected outputs:

1.) 0
2.) The provided argument is of a wrong type
3.) The provided argument is of a wrong type

Remark to 2.) Because this is not valid in decimal notation
Remark to 3.) Because this is not a valid number

**Comment by jarro2783** [comment]
Lol, it looks a bit broken doesn't it. I'll take a look thanks.
