### ISSUE TITLE
Adding help text after `[OPTION...]` (or hiding help text intro)

### ISSUE THREAD

**Issue by Malvineous** [jarro2783/cxxopts#82]
My code (which I am moving to cxxopts) currently displays the usage like this, when `--help` is passed:

    Usage: gamecomp -t <type> < infile > outfile

However cxxopts displays it like this:

    Usage:
      gamecomp [OPTION...]

I can't see a way to write any text after `[OPTION...]`, so that I can put `< infile > outfile` onto the end of that line.

I also can't see a way to hide the intro text and usage line entirely so I can write it myself with my own code, and have cxxopts only display the bare argument list.

Is one of these things possible?  Given the choice, being allowed to omit the parameters to `cxxopts::Options()` to cause it to skip displaying the intro text would be the most flexible I think.  I tried passing in two blank strings but I still get the `Usage:` line.

**Comment by Malvineous** [comment]
Just a +1 for hiding the default intro, because `[OPTION...]` doesn't really suit one of my programs (it has both options and actions which should appear differently on the command line, not just lumped together as 'options').

I found I can repurpose the positional help text to get text after the `[OPTION...]` but that only works if there are actual positional parameters - the help text won't appear unless you've called `parse_positional()` before displaying the help - and unfortunately there aren't positional parameters in my case!

**Comment by jarro2783** [comment]
No that's hard coded at the moment, but is easily changed. Do you want it to be `program_name custom_text` or to completely override the first line?

**Comment by Malvineous** [comment]
`program_name custom_text` would probably be fine, then `custom_text` could just default to `[OPTION...]`.  Thanks!
