### ISSUE TITLE
Positional parameters - overload ambiguity

### ISSUE THREAD

**Issue by Malvineous** [jarro2783/cxxopts#83]
Just went off the example and tried to use position parameters, like this:

    options.parse_positional({"archive"});

However this fails with the errors:

    error: call of overloaded ‘parse_positional(<brace-enclosed initializer list>)’ is ambiguous
       options.parse_positional({"archive"});
                                           ^
    ./cxxopts.hpp:1589:1: note: candidate: void cxxopts::Options::parse_positional(std::__cxx11::string)
     Options::parse_positional(std::string option)

    ./cxxopts.hpp:1596:1: note: candidate: void cxxopts::Options::parse_positional(std::vector<std::__cxx11::basic_string<char> >)
     Options::parse_positional(std::vector<std::string> options)

It seems if you only have one variable for the positional parameters to go into, you should not use a vector and use a string instead.  I don't suppose there's any way to make the syntax uniform no matter how many parameters you specify?  Maybe with an `std::initializer_list` overload too, or instead of them both?

**Comment by jarro2783** [comment]
I didn't realise that was ever a valid overload for `std::string`, I think in this case adding an `initializer_list` option is the best way to fix it.
