### ISSUE TITLE
Segfault when using a ParseResult returned from function

### ISSUE THREAD

**Issue by adgaudio** [jarro2783/cxxopts#85]
Hello!

Thank you for providing this library!  I'm excited about it.  I'm a bit new to c++, so please forgive me if this issue is due to my ignorance.  

I define a function called parseArgs, and call it from my main function like this:

```
#include <iostream>
#include "cxxopts.hpp"

cxxopts::ParseResult parseArgs(int argc, char** argv) {
  cxxopts::Options options("foo", "foo bar");
  options.add_options()
    ("atest", "test", cxxopts::value<std::string>()->implicit_value("a.out"))
  ;
  return options.parse(argc, argv);
}

int main(int argc, char **argv) {
  cxxopts::ParseResult args = parseArgs(argc, argv);
  std::string value = args["atest"].as<std::string>();
  return 0;
}
```

The code builds without warning.  I replaced the code in example.cpp with above, compile it into an executable.  However, when I run the executable, I get a segfault:

```
 $ ./src/example --atest test
zsh: segmentation fault (core dumped)  ./src/example --atest test
```

If I comment out the following line, recompile and run, the segfault disappears:  
``` std::string value = args["atest"].as<std::string>();```

Do you have any idea why this happens?  Or am I doing something incorrectly? 

Thank you in advance for your time!

**Comment by jarro2783** [comment]
The `ParseResult` object refers to an object from the `Options` object that created it, so you can only use a `ParseResult` object as long as `Options` stays in scope.

Unfortunately C++ has no way of enforcing that. I hadn't thought of this though, so I could at least document it.

**Comment by adgaudio** [comment]
Okay, thank you.  It might be worth throwing an error instead of segfault, too, by adding a try catch around (I think) this line: https://github.com/jarro2783/cxxopts/blob/master/include/cxxopts.hpp#L1100

I don't know if that will affect performance negatively.

Cheers!

**Comment by jarro2783** [comment]
No that doesn't work. You can't catch a segfault because it's a signal raised by the kernel when you access invalid memory. Exceptions in C++ are a language specific mechanism which are entirely separate to OS signals.
