### ISSUE TITLE
regex_error

### ISSUE THREAD

**Issue by paulbeerkens** [jarro2783/cxxopts#88]
I am trying to use the library on gcc6.2 running with c++14.

During static initialization I get an regex_error exception on this line:

cxxpopts.hpp:433

std::basic_regex<char> integer_pattern
        ("(-)?(0x)?([1-9a-zA-Z][0-9a-zA-Z]*)|((0x)?0)");

When I copy this line in a simple app I get the same error.

**Comment by paulbeerkens** [comment]
Oops. This project was using gcc4.8 which does not have proper regex support. Sorry my bad.

**Comment by jarro2783** [comment]
No problems.
