### ISSUE TITLE
Add support for std::optional

### ISSUE THREAD

**Issue by milipili** [jarro2783/cxxopts#93]
It would make things probably easier to be able to directly use `std::optional`:

```
std::optional<std::string> name;
[...]
options.add_options()("n,name", "Dummy name", cxxopts::value<std::optional<std::string>>(name));
[...]
if (name.has_value()) {
    [...]
}
```

We can achieve something similar but with a different approach, but working directly on values (instead of dictionaries) would seem more natural.

**Comment by jarro2783** [comment]
That seems reasonable, and hopefully isn't too difficult.

I still have C++11 support as an explicit goal, but that's what `#ifdef` is for. There's no reason it can't work if you're on something that supports it.

**Comment by milipili** [comment]
You probably know it already, but just in case: http://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros.
So hopefully `__cpp_lib_optional` should be enough.

**Comment by jarro2783** [comment]
Yeah thanks.

**Comment by milipili** [comment]
Thanks :)
