### ISSUE TITLE
Is there documentation for cxxopts

### ISSUE THREAD

**Issue by winny-** [jarro2783/cxxopts#97]
Is there online documentation for cxxopts?

**Comment by jarro2783** [comment]
Yes. The [readme](https://github.com/jarro2783/cxxopts/blob/master/README.md) and the [wiki](https://github.com/jarro2783/cxxopts/blob/master/README.md).

**Comment by winny-** [comment]
Thanks!

**Comment by patrikhuber** [comment]
@jarro2783 Just a nitpick but your "wiki" link here links to the readme too, not the wiki ;-)

**Comment by jarro2783** [comment]
Ah oops. I'll fix that.
